### PR TITLE
fix(#6292): scroll speed for timepicker on mobile devices to high

### LINKED ISSUE #6292: scroll speed for timepicker on mobile devices to high
## Description  
The touch controls for the time picker on mobile devices are too sensitive. For every pixel you move your finger, the spinner does one step, which is way to fast.

 * igniteui-angular version: 8.2.x
 * browser: Safari Mobile

## Steps to reproduce  

1. Open time picker dialog on mobile device
2. Drag up or down with your finger

## Result  
When moving the distance of one entry, it does to many steps

## Expected result  
When moving the distance of one entry, it should do one step

### PR DESCRIPTION
**Pull request by robertjanetzko**
Closes #6292   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by Lipata** [comment]
@robertjanetzko, thank you for contributing to our product!

For touch gestures, we are using hammers.js. We are currently trying to configure the scroll step using hammer.js settings and if we succeed we will inform you and we will prefer to use such an implementation. Please tell me how you want to proceed with the following pull request - do you prefer guidance and to apply comments that we will suggest, or you prefer that we take care of that implementation. Thank you!

**Comment by Lipata** [comment]
@robertjanetzko I have put a comment with an update on the #6292  issue.

**Comment by kdinev** [comment]
@Lipata @robertjanetzko @radomirchev This has been sitting in the queue for quite some time. Please consider it for the upcoming sprint.

**Comment by Lipata** [comment]
@robertjanetzko we will take care of that feature in the future. I will close that PR.

**Pull request closed without merging**
