### PR TITLE
fix(migrations): remove licensed package from group

### PR DESCRIPTION
**Pull request by Lipata**
#13467
The fix comes with a task in the licensed release pipeline, which replaces "igniteui-angular" with "@infragistics/igniteui-angular"

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — CHANGES_REQUESTED** [review]
@Lipata With the change as is, there will be a single update group - `igniteui-angular`. If I'm using the `@infragistics/igniteui-angular` package, however, then `igniteui-angular-i18n` would not be updated together with it. Same applies to `@igniteui/angular-schematics`.

**Comment by kdinev** [comment]
> @Lipata With the change as is, there will be a single update group - `igniteui-angular`. If I'm using the `@infragistics/igniteui-angular` package, however, then `igniteui-angular-i18n` would not be updated together with it. Same applies to `@igniteui/angular-schematics`.

You have to check this, but I believe in order to handle this, either a second update group needs to be defined, or the current update group needs to be changed when building the licensed package.

**Comment by Lipata** [comment]
@kdinev in the licensed pipeline there is a task that replaces "igniteui-angular" with "@infragistics/igniteui-angular" as a group name. You can check the latest licensed beta 6 and see the group is the following:

image

**Comment by Lipata** [comment]
Defining a second group is not possible, unfortunatelly.

**Review by kdinev — APPROVED** [review]

**Comment by valadzhov** [comment]
Reverting the status to "In development". When updating `igniteui-angular` or `igniteui-angular-i18n` with `ng update {{package}} --next` in an **unlicensed** project updating either one of the packages updates the other as well. In a **licensed** project `igniteui-angular-i18n` doesn't update `igniteui-angular` but `igniteui-angular` updates `igniteui-angular-i18n`.

**Review by damyanpetev — APPROVED** [review]

**Pull request merged**
