### PR TITLE
fix(toast): isVisible property binding - master

### LINKED ISSUE #8207: Setting isVisible does not show the toast
## Description  
`IgxToast` has property `isVisble`. If toast is not shown and you set `isVisible` to `true` toast does not show. Same if toast is visible and you set the property to `false`.

 * igniteui-angular version: 10.2
 * browser: all

## Steps to reproduce  

1. Create `igxToast`
2. Set `isVisible` to `true`

## Result  
Toast does not appear.

## Expected result  
Toast should appear.

## Notes
After merging PR #8197 we may consider deprecating `isVisble` and use `collapsed`. Also we could change `show`/`hide` methods to `open`/`close` as well as all related events.

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #8207 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — APPROVED** [review]

**Review by hanastasov — CHANGES_REQUESTED** [review]
Please add a test that verifies setting isVisible actually opens/shows the toast.

**Review by hanastasov — CHANGES_REQUESTED** [review]
Using event handlers for executing expectations results in false negative test - if event handlers are not called, test will still succeed, while there is a bug (toast is not actually opened and event is not emitted).
It's better to use jasmine spyOn to test if event is emitted.

**Review by zdrawku — DISMISSED** [review]
Well done. I see that the changes regarding the migration are applied as well.

**Review by hanastasov — CHANGES_REQUESTED** [review]
1. visibility is updated by the toggle() method
2. should open and close toast when set values to isVisible

The above tests implementation result in false negative tests. Please refactor those.

**Review by hanastasov — APPROVED** [review]

**Review by zdrawku — APPROVED** [review]

**Pull request merged**
