### PR TITLE
Add more APIs to manipulate dimensions/values more easily.

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
@simeonoff @dkamburov What do you think about these APIs? Let me know if I've missed some API you think would be useful or if you have any suggestions on improving the existing ones.

**Comment by simeonoff** [comment]
> @simeonoff @dkamburov What do you think about these APIs? Let me know if I've missed some API you think would be useful or if you have any suggestions on improving the existing ones.

LGTM, much cleaner than before.

**Review by simeonoff — DISMISSED** [review]

**Comment by skrustev** [comment]
Things I noticed:
1) `removeDimension` and `removeValue` methods delete the last element in array if the provided input is not present.
2) I see that we don't have getter for values like for dimensions. The current getter for `values` returns only the `enabled` ones. Should we have one for them as well in this case?

**Comment by MayaKirova** [comment]
@skrustev 1, 2 and 3 should be resolved now. 
Reg. 4 - I don't think we need a separate getter just for the `this.pivotConfiguration.values`. Dimensions can be in 3 different collections so we need  a more specific getter, but values are always in just one.

Reg.5 - We do have a limitation that we cannot have dimensions with the same memberName. Would setting a different memberName for each inserted dimension fix the issue?

**Review by mddragnev — DISMISSED** [review]

**Review by simeonoff — APPROVED** [review]

**Review by ChronosSF — APPROVED** [review]

**Pull request merged**
