### PR TITLE
feat(dropdown): update indigo styles

### LINKED ISSUE #234: Indigo: Update dropdown component

### PR DESCRIPTION
**Pull request by SisIvanova**
Related to IgniteUI/igniteui-theming/issues/234

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by didimmova** [comment]
The first item margin-block is not 0, as in the WC PR

**Comment by AnjiManova** [comment]
- paddings are 3px, but the border should be placed inside (in the kit, the space between the border and the active/hover background is 2px, not sure how you are going to implement it, but below you can see a reference from the kit)
image
image

**Comment by AnjiManova** [comment]
- the applied elevation is right (Elevation 3), but I don't think that the style of the elevation is defined the same as in the kit

**Comment by AnjiManova** [comment]
The overline style is wrong. There is merged pr with the overline style, but still the change is not visible in this pr.

image

**Comment by AnjiManova** [comment]
The Focused & Hover state is logical and correct compared to the other states, and it should look like this IMO, but I'm not sure if it's by design ... @andiesm813 please confirm

**Comment by AnjiManova** [comment]
The text should be white 80% not Grays.800

image

**Comment by andiesm813** [comment]
@SisIvanova i couldnt run the samples from this branch. I got some errors:

image

**Comment by andiesm813** [comment]
> * the applied elevation in Light is right (Elevation 3), but I don't think that the style of the elevation is defined the same as in the kit
> * the applied elevation in Dark is right (Elevation 2), but I'm not sure the style is the defined one in Figma

I have to create a separate issue for all elevations. I was waiting to finish the last one i created so i could include all of them in the issue. All elevations are defined in the figma. They just havent been updated in the implemented elevations.

**Comment by andiesm813** [comment]
> The Focused & Hover state is logical and correct compared to the other states, and it should look like this IMO, but I'm not sure if it's by design ... @andiesm813 please confirm
> 
> Same for Active/Focused & Hover

I will confirm when i can see it... i couldnt run the sample... @AnjiManova

**Comment by AnjiManova** [comment]
- after selecting an item and reopening the dropdown, the item stays focused
image

**Comment by SisIvanova** [comment]
> The overline style is wrong. There is merged pr with the overline style, but still the change is not visible in this pr.
> 
> image

The font-size is 11px and the line-height is 15px. I believe these are the correct sizes.

**Comment by SisIvanova** [comment]
> * the applied elevation in Light is right (Elevation 3), but I don't think that the style of the elevation is defined the same as in the kit
> * the applied elevation in Dark is right (Elevation 2), but I'm not sure the style is the defined one in Figma

All elevations will be updated in a separate PR

**Pull request closed without merging**
