### PR TITLE
chore(typedoc): hide some declarations from typedoc document

### LINKED ISSUE #2858: Typedoc API task generates non-public exports
### Description  
Typedoc API task generates globals not exported through `public_api.ts` or in other words stuff that are not intended for user apps and can't be imported `from 'igniteui-angular';`.

I realize the typedoc generation was moved to the entire project folder for search purposes and we can go through and mark stuff `@hidden`. However, as you can see from the links below even on older prod deploys where non-public API is generated - the search is still iffy. Might not be related issues after all.

### Steps to reproduce  
Try some of the following links.
> **Note:** This list is by no means exhaustive, just the few I noticed. There are prob way more using master.

Enums:
`ExcelFileTypes` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/enums/excelfiletypes.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/enums/excelfiletypes.html))
`ExcelFolderTypes` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/enums/excelfoldertypes.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/enums/excelfoldertypes.html))
`ICON_POSITION` [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/enums/icon_position.html)

Classes:
`AppFile` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/appfile.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/appfile.html))
`CharSeparatedValueData` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/charseparatedvaluedata.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/charseparatedvaluedata.html))
`ContentTypesFile` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/contenttypesfile.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/contenttypesfile.html))
`DataGenerator` [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/datagenerator.html)
`ExportUtilities` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/exportutilities.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/exportutilities.html))
`HVirtualHelperComponent` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/hvirtualhelpercomponent.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/hvirtualhelpercomponent.html))
`IgxAmPmItemDirective` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxampmitemdirective.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxampmitemdirective.html))
`IgxComboAddItemDirective` [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxcomboadditemdirective.html)
`IgxDialogActionsDirective` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxdialogactionsdirective.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxdialogactionsdirective.html))
`IgxHourItemDirective` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxhouritemdirective.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxhouritemdirective.html))
`MaskHelper` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/maskhelper.html) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/maskhelper.html))
`IgxScrollInertiaDirective` [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxscrollinertiadirective.html)

Variables:
`MASK_FLAGS` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/globals.html#mask_flags) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/index.html#mask_flags))

Functions:
`DeprecateClass`, `DeprecateMethod`, `DeprecateProperty`

Object literals:
`KEYS` ([prod](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/globals.html#keys) | [staging](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/index.html#keys))

### Result  
Non public API is included in the generation.

### Expected result  
API pages should generate from public API only

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #2858

### CODE REVIEW

**Comment by damyanpetev** [comment]
Looking at https://github.com/TypeStrong/typedoc/issues/639 generating just the exported API might not be supported at all, so yeah `@hidden` it is.
There are more than those though, will update with a full list.

**Comment by damyanpetev** [comment]
Made some more updates for exports I'm certain shouldn't be public. The once left might need verification first, here's the ones that will error out with "igniteui-angular/src/public_api has no exported member" when testing on this branch:
```ts
import {
ColumnChooserBase,
ColumnChooserItemBase,
DisplayContainerComponent,
DocPropsExcelFolder,
ExcelElementsFactory,
ExcelStrings,
IgxColumnHidingItemDirective,
IgxComboDropDownComponent,
IgxComboItemComponent,
IgxDropDownItemBase,
IgxDropDownItemComponent,
IgxExpansionPanelBodyComponent,
IgxGridNavigationService,
IgxGridToolbarComponent,
IgxGridTransactionPipe,
IgxItemListDirective,
IgxProcessBarTextTemplateDirective,
IgxSelectionAPIService,
IgxTreeGridFilteringPipe,
IgxTreeGridPagingPipe,
IgxTreeGridSortingPipe,
RootExcelFolder,
RootRelsExcelFolder,
SimpleFilteringStrategy,
TablesExcelFolder,
ThemeExcelFolder,
TreeGridFilteringStrategy,
VirtualHelperComponent,
WorksheetData,
WorksheetDataDictionary,
WorksheetsExcelFolder,
WorksheetsRelsExcelFolder,
XLExcelFolder,
XLRelsExcelFolder,
CancelableEventArgs,
IExcelFile,
IExcelFolder,
IExpansionPanelEventArgs,
IValueChangedEventArgs,
OverlayCancelableEventArgs,
isNavigationKey,
} from 'igniteui-angular';
```
I assume all the excel stuff are to be hidden, right? @gedinakova

**Comment by gedinakova** [comment]
None of the Excel, ColumnChooser and TreeGrid related items should be visible.

**Comment by damyanpetev** [comment]
After latest changes what's left in the API docs are the following not exported items:
```ts
import {
    DisplayContainerComponent,
    IgxExpansionPanelBodyComponent,
    IgxProcessBarTextTemplateDirective,
    SimpleFilteringStrategy,
    VirtualHelperComponent,
    CancelableEventArgs,
    IExpansionPanelEventArgs,
    IValueChangedEventArgs
} from 'igniteui-angular';
```

**Pull request merged**
