### PR TITLE
IgxGrid Column Pinning (API)

### LINKED ISSUE #677: IgxGrid Column and Row Pinning
### Description  ###

I would like as as user to be able to Pin my columns and my row in the Grid. I would like to be able to pin my column on the right and on the left end of the Grid, so when i scroll let and right the columns stay visible. I would like to be able to pin a row from the Grid to the top of the grid so that when I Scroll up and down the row stays pinned to the top.

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #677  .  

Spec: https://github.com/IgniteUI/igniteui-angular/wiki/Column-Pinning

Before it can be merged a few issues need to be resolved:

- [x] #712 - finalizing unit tests
- [x] #714 Finalizing styling - filtering dropdown issue to be resolved - @simeonoff 
- [x] #748 Grid ReadMe, Grid DocFX updates, Changelog
- [x] #742 bug
- [x] #743 bug
- [x] #745 bug
- [x] Manual tests after right pinning removal

### CODE REVIEW

**Comment by ChronosSF** [comment]
@simeonoff - as we dropped right pinning we don't need the filter UI container to have position fixed. A lot of tests also fail because they expect it too have offsetParent.

**Comment by ChronosSF** [comment]
@mpavlinov , @kdinev - documentation artifacts are already in the branch or PR-ed to DocFX, if you identify other items to be added, please include them to the checklist. IMO this can be merged after successful reviews.

**Comment by kdinev** [comment]
@ChronosSF Any testing? Should this be marked as `status: verified`?

**Comment by ChronosSF** [comment]
me and @dkamburov  will do another round of tests to ensure nothing regressed from the removal of the right pinning.

**Comment by kdinev** [comment]
@ChronosSF There's a conflict currently.

**Comment by ChronosSF** [comment]
All high severity bugs found are actually in igxFor so I am removing them from the checklist.

This can be considered tested.

**Pull request merged**
