### PR TITLE
feat(themes): implement updated Indigo UI theme

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #  

- [x] Avatar
- [x] Badge
- [x] Banner
- [x] Button
- [x] Button Group
- [x] Card
- [x] Carousel
- [x] Checkbox
- [x] Divider
- [x] Expansion Panel
- [x] Icon
- [x] Icon Button
- [x] Input
- [x] Radio
- [x] Snackbar

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by sbayreva** [comment]
**Avatar**
1. In Light Mode the color of the icon should be Grays 600

**Comment by sbayreva** [comment]
**Checkbox**
1. In Light Mode label color in Invalid Hover state should be Grays 900
2. In Light and Dark mode label font should be Body 2
3. In Dark Mode Error color of Invalid state should be Error 400
4. In Dark Mode Error color of Invalid Hover state should be Error 300
5. In Dark Mode the color of the label in Invalid Hover state should be white

**Comment by sbayreva** [comment]
**Dialog**
1. In Dark Mode the elevation should be 23

 **In Both Dark and Light Mode**
1. The font of the message should be Body 1 
2. The size of the buttons should be Medium
3. The Left Button should be Outlined and The Right Button should be Contained

**Comment by AnjiManova** [comment]
**Button**
1. Contained/Large in Light and Dark theme -> The space between the Icon and Label in the Indigo UI kit is 8px; currently, the implementation is 12px.

**Comment by AnjiManova** [comment]
**Colors**

The Surface Color in the Dark theme should be changed to #1E1F24 - @andiesm813 confirm it. 

Currently, it is #1E1E1E [check the link here](https://github.com/IgniteUI/igniteui-theming/blob/b7f621ee28c8d9f97637c17fb6164b2fa0083a78/sass/color/presets/dark/_indigo.scss#L227)

**Comment by imincheva** [comment]
**Card:**
Avatar should be aligned to the vertical center of the header.
Buttons should be size medium.

**Comment by imincheva** [comment]
**Card:**
Avatar should be aligned to the vertical center of the header.
Buttons should be size medium.

**Comment by imincheva** [comment]
**Input**
The gap between prefix and placeholder and the one between placeholder and suffix should be 8px, not 4px
The color of the bottom border in disabled state in dark mode should be updated to white 15%

**Comment by imincheva** [comment]
**Banner**
no visual discrepancies

**Comment by andiesm813** [comment]
> **Checkbox**
> 
> 1. In Light Mode label color in Invalid Hover state should be Grays 900
> 2. In Light and Dark mode label font should be Body 2
> 3. In Dark Mode Error color of Invalid state should be Error 400
> 4. In Dark Mode Error color of Invalid Hover state should be Error 300
> 5. In Dark Mode the color of the label in Invalid Hover state should be white

I couldn't check these, cos i didnt find the checkbox samples page anywhere.... but all the comments are good!

**Comment by andiesm813** [comment]
> **Dialog**
> 
> 1. In Dark Mode the elevation should be 23
>    @andiesm813 Please, confirm the elevation in Dark Mode.
> 
> **In Both Dark and Light Mode**
> 
> 1. The font of the message should be Body 1
> 2. The size of the buttons should be Medium
> 3. The Left Button should be Outlined and The Right Button should be Contained

Confirmed. That should be the elevation for the dark mode.
Regarding point #3, the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both. 


image

In the "Fluent dialog" example, the button types are correct... and that's a valid positioning, although we use it in the other order. The other comments apply to all of the dialog samples (button size, msg text size).

**Comment by andiesm813** [comment]
> **Icon Button**
> 
> Light Theme
> 
> 1. Contained Icon Button - if we follow the logic behind the contained button, the same logic is implemented for the Flat and Outlined buttons as well. The icon should be white 80%, not 100%, and the focus border should be primary.400 50%, not grays.900 15%. The disabled icon color should be white 30%, based on the above.
> 
> Dark Theme
> 
> 1. Flat Icon Button - the disabled color of the icon in the UI kit is white 20%, and the implementation is grays.900 20%
> 2. Contained Icon Button - if we follow the logic behind the contained button implemented for the Flat button as well, the icon should be white 80%, not 100%, and the focus border should be primary.400 50%, not grays.900 15%. The disabled icon color should be white, 20%, based on the above.
> 3. Outlined Icon Button - same as the Contained, the icon color in the idle state should be white 80%, and the focused border should be white 20% -> In the Light theme, the button follows the Outlined Button style.
> 
> @andiesm813 should confirm this and give you more guidelines if it's needed.

**Light theme**
Those corrections are ok @AnjiManova 100% confirmed.

**Dark theme**
1. Agreed
2. Currently the implemented disabled icon color is white 40%, and lije Anji said it should be 20%.
3. As well as the other issue mentioned, the disabled foreground color should be white 20%  and the implementation is grays.900 20%.

**Comment by andiesm813** [comment]
> the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both.

**Other CARD fixes:**
1. In the card actions, the text buttons should be 1 outlined, 1 contained. The primary action should be "contained" and the secondary action should be "outlined". 
2.  When all content is hidden, except for actions, the top padding should be also 16px. Currently it's 8px.

image
3. In both light and dark modes designs, cards are not supposed to have elevation. I guess you have the option in the implemented components. So i changed the styling of the --ig-elevation-4 and --ig-elevation-6 used in cards in the figma file.

**Comment by andiesm813** [comment]
> **Banner** no visual discrepancies

I do have a couple of discrepancies:
1. Buttons used in the banner are set to medium size.
2. There is this min-height set to the banner actions, and it's causing additional top/bottom padding inside the banner. Can we change that for this theme or not? if not, it's fine! ;)

image

**Comment by andiesm813** [comment]
**Radio Group**

I don't see the focused states in both Light / Dark Themes, but the colors are correctly set in the styles.

**Comment by andiesm813** [comment]
@imincheva 
I see the gap between prefix/suffix and placeholder correctly, set to 4px.

image

**Comment by andiesm813** [comment]
> **Input** The gap between prefix and placeholder and the gap between placeholder and suffix should be 8px, not 4px The color of the bottom border in disabled state in dark mode should be updated to white 15%

@imincheva 
I see the gap between prefix/suffix and placeholder correctly, set to 4px.

image

**Comment by sbayreva** [comment]
**Radio Group**
1. Radio Group Horizontal: space between separate radio buttons should be 16px
2. The color of the Disabled Checked (filled) variants in Light and Dark Mode should be Primary 400 with 50% opacity

**Comment by SisIvanova** [comment]
> > the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both.
> 
> **Other CARD fixes:**
> 
> 1. In the card actions, the text buttons should be 1 outlined, 1 contained. The primary action should be "contained" and the secondary action should be "outlined".
> 2. When all content is hidden, except for actions, the top padding should be also 16px. Currently it's 8px.
> 
> image
> 
> 3. In both light and dark modes designs, cards are not supposed to have elevation. I guess you have the option in the implemented components. So i changed the styling of the --ig-elevation-4 and --ig-elevation-6 used in cards in the figma file.

- In WC and Angular we have two types of cards - elevated and outlined, that's why in the samples some of the cards have elevation. --ig-elevation-4 is the elevation level of the resting elevation and --ig-elevation-6 is for the hover elevation.
- About the action buttons - users can set the type of button that they would like to use so we don't want to limit them by explicitly setting the type to 'contained' or 'outlined'

**Comment by SisIvanova** [comment]
> > **Dialog**
> > 
> > 1. In Dark Mode the elevation should be 23
> >    @andiesm813 Please, confirm the elevation in Dark Mode.
> > 
> > **In Both Dark and Light Mode**
> > 
> > 1. The font of the message should be Body 1
> > 2. The size of the buttons should be Medium
> > 3. The Primary action should be with Contained button and the Secondary with Outlined.
> 
> Confirmed. That should be the elevation for the dark mode. Regarding point #3, the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both.
> 
> image
> 
> In the "Fluent dialog" example, the button types are correct... and that's a valid positioning, although we use it in the other order. The other comments apply to all of the dialog samples (button size, msg text size).

- Same as the card actions - it's up to the users which type of button they will use.

**Comment by andiesm813** [comment]
> > **Input** The gap between prefix and placeholder and the gap between placeholder and suffix should be 8px, not 4px The color of the bottom border in disabled state in dark mode should be updated to white 15%
> 
> @imincheva I see the gap between prefix/suffix and placeholder correctly, set to 4px.
> 
> image

That gap was ok for input group.... but for "searchbox" (input type "search"), the gap should be 8pc and it also has 8px left and right inner padding. 

image

**Comment by AnjiManova** [comment]
**Button Group**

1. The default Button size is Medium, and the Buttons should be 28px in height, not 32.
2. The Hover state borders overlap; in WebC, they are z-index: -1. We could apply this in Angular as well. image

Light Theme
1. There is no defined Active state, but we could fix the border and apply the Idle background color. @andiesm813 I need your confirmation here. image
2. The icon in the Focused state should be grays.600 image

Dark Theme
1. There is no defined Active state, but we could apply the Idle background color. @andiesm813 I need your confirmation here.image
2. The Icon in the Focused state should be white 80% 
image

**Comment by andiesm813** [comment]
> **Radio Group**
> 
> I don't see the focused states in both Light / Dark Themes, but the colors are correctly set in the styles.

I should've explained more what i meant about not seeing the focused states in the radio items. I meant these: 
image

**Comment by andiesm813** [comment]
> > > the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both.
> > 
> > 
> > **Other CARD fixes:**
> > 
> > 1. In the card actions, the text buttons should be 1 outlined, 1 contained. The primary action should be "contained" and the secondary action should be "outlined".
> > 2. When all content is hidden, except for actions, the top padding should be also 16px. Currently it's 8px.
> > 
> > image
> > 
> > 3. In both light and dark modes designs, cards are not supposed to have elevation. I guess you have the option in the implemented components. So i changed the styling of the --ig-elevation-4 and --ig-elevation-6 used in cards in the figma file.
> 
> * In WC and Angular we have two types of cards - elevated and outlined, that's why in the samples some of the cards have elevation. --ig-elevation-4 is the elevation level of the resting elevation and --ig-elevation-6 is for the hover elevation.
> * About the action buttons - users can set the type of button that they would like to use so we don't want to limit them by explicitly setting the type to 'contained' or 'outlined'

Ok! sounds good @SisIvanova ... let's not limit them... As long as the other fixes are applied, i'm good! Other fixes meaning: avatar alignment, button sizing, padding when only actions are visible, and elevation style updates (that you can get from the latest ui kit update i did on the card). Thanks!

**Comment by andiesm813** [comment]
> > > **Dialog**
> > > 
> > > 1. In Dark Mode the elevation should be 23
> > >    @andiesm813 Please, confirm the elevation in Dark Mode.
> > > 
> > > **In Both Dark and Light Mode**
> > > 
> > > 1. The font of the message should be Body 1
> > > 2. The size of the buttons should be Medium
> > > 3. The Primary action should be with Contained button and the Secondary with Outlined.
> > 
> > 
> > Confirmed. That should be the elevation for the dark mode. Regarding point #3, the primary action should be "contained" and the secondary action should be "outlined". So depending on the positioning of both.
> > image
> > In the "Fluent dialog" example, the button types are correct... and that's a valid positioning, although we use it in the other order. The other comments apply to all of the dialog samples (button size, msg text size).
> 
> * Same as the card actions - it's up to the users which type of button they will use.

Agreed @SisIvanova ! again, as long as the other styling changes are made as well! (button sizing, elevation dark mode, message font size and button size). ;)

**Comment by andiesm813** [comment]
> 3\. All Buttons in the UI kit use Body 2 style for the labels.

Correct about the Labels comment: Body 2 and not uppercase (normal case).

**Comment by andiesm813** [comment]
> **Button Group**
> 
> 1. The default Button size is Medium, and the Buttons should be 28px in height, not 32.
> 2. The Hover state borders overlap; in WebC, they are z-index: -1. We could apply this in Angular as well. image
> 3. All Buttons in the UI kit use Body 2 style for the labels.
> 
> Light Theme
> 
> 1. There is no defined Active state, but we could fix the border and apply the Idle background color. @andiesm813 I need your confirmation here. image
> 2. The icon in the Focused state should be grays.600 image
> 
> Dark Theme
> 
> 1. There is no defined Active state, but we could apply the Idle background color. @andiesm813 I need your confirmation here.image
> 2. The Icon in the Focused state should be white 80%
> 
> image

I dont really have strong feelings towards this state.... but if we have to have it, then it would be a mix of hover and focused states, and no ripple effect (to be consistent with the default button styles, and because the ripple effect sounds to me more like a material thing):

image

**Light theme:** 

- background grays.200
- border grays.500
- outer focused border grays900 15%
- foreground grays.800
- icons grays700

**Dark theme:** 

- background white 10%
- border white 30%
- outer focused border white 20%
- foreground & icons white

**Comment by andiesm813** [comment]
**Snackbar**
No visual discrepancies

**Comment by andiesm813** [comment]
Input Group
A couple of more issues i found:

**Light theme:**

- idle-text-color should be set to grays.600, not grays800 (like the filled-text-color). Shouldn’t it be the same as the placeholder-color? 

**Dark theme**

- idle-text-color should be set to white 60%, not white 80% (like the filled-text-color). Shouldn’t it be the same as the placeholder-color?
- --focused-text-color should be the same as --filled-text-hover-color (white 100%).

**Comment by andiesm813** [comment]
> **Dialog**
> 
> 1. In Dark Mode the elevation should be 23
>    @andiesm813 Please, confirm the elevation in Dark Mode.
> 
> **In Both Dark and Light Mode**
> 
> 1. The font of the message should be Body 1
> 2. The size of the buttons should be Medium
> 3. The Primary Action should be with Contained Button and the Secondary with Outlined.

Also both elevation styles that light and dark dialogs are using need to be updated to the following values:

**Shadow 24 (light theme)**
These should be the default settings of the shadow style:
box-shadow:0 0px 16px 0 #24252c66 (grays.900 40%)


**Shadow 23 (dark theme)**
These should be the default settings of the shadow style:
box-shadow:0 0px 16px 0 #0000004d (Black 30%)

**Comment by andiesm813** [comment]
**Card**
I know users can change the style of the buttons and whatnot, but by design, the avatar type is set to circle. Can we default to that? It's the theme :)

**Comment by imincheva** [comment]
**Card:**
In this example, the 2px margin-bottom on subtitle is missing. Also, when you remove the subtitle, the title isn't properly aligned to the vertical center
image

On these 3 examples the top padding on the actions is still 8px. Andie requested for all paddings to be 16px
image
image
image

**Comment by imincheva** [comment]
**Banner:**
(IGNORE IF IRRELEVANT) The button inside the Banner is still set to size large, although the size of the banner actions is set to medium.
image

**Comment by AnjiManova** [comment]
**Carousel**

The icon size in the implementation is Large (24x24) it should be small (14x14)

For the Hover states (Indicatior) and Disabled states (navigation Buttons), @andiesm813 should provide more details.

**Comment by imincheva** [comment]
**Badge:**
Font-weight on the text badge should be 700 (bold)
Icon size on the icon badge should be 12x12px. Currently it's 11x11px.

**Comment by sbayreva** [comment]
**Divider:**
The size of the dashes and the gap between them on the dashed diver don't correspond with the ones in the UI kit. Both of them should be 3px

**Comment by andiesm813** [comment]
@SisIvanova the only thing i still see not updated are the elevation styles that we talked about in the chat:

**DIALOGS**

/* Elevations/Shadow 23 */
box-shadow: 0px 0px 16px 0px rgba(0, 0, 0, 0.30);

/* Elevations/Shadow 24 */
box-shadow: 0px 0px 16px 0px rgba(36, 37, 44, 0.40);

**CARD**

/* Elevations/Shadow 04 */
box-shadow: 0px 2px 12px 0px rgba(36, 37, 44, 0.10);

/* Elevations/Shadow 06 */
box-shadow: 0px 2px 12px 0px rgba(36, 37, 44, 0.20);

**Comment by andiesm813** [comment]
@SisIvanova we just merged a LAST change to the button group. There was an issue with the borders (strokes) overlapping because of their transparency (in the dark theme), and we made a tiny change to a couple of border colors, in order to prevent this! In the light theme, we also adjusted a border color in the disabled button, because same issue was happening.

image

**Comment by imincheva** [comment]
**Expansion Panel:**
- In light mode the disabled icon color should be grays.900 20% opacity; currently, I think it's grays.400
- In dark mode the disabled icon color should be white 20% opacity; currently, I think it's grays.400

**Comment by andiesm813** [comment]
> **Expansion Panel:**
> 
> * In light mode the disabled icon color should be grays.900 20% opacity; currently, I think it's grays.400
> * In dark mode the disabled icon color should be white 20% opacity; currently, I think it's grays.400

Actually in the CSS they seem to be ok :)  since i couldnt see the disabled arrow state (because the sample looked weird when disabled), i just checked the CSS and the disabled colors seemed fine for both themes:

image

**Comment by AnjiManova** [comment]
The border colors in the Button Group are changed in the following states and the changes are related only to the **unselected buttons**

Light Theme:
- Disabled - the border is changed from **grays.900 15%** to **grays.100 solid**

Dark Theme:
- Idle - the border is changed from **white 20%** to **grays.100 solid**
- Hover - the border is changed from **white 30%** to **grays.200 solid**
- Focused - the border is changed from **white 20%** to **grays.100 solid**
- Active - the border is changed from **white 30%** to **grays.200 solid**
- Focused & Active - the border is changed from **white 30%** to **grays.200 solid**
- Focused & Hover - the border is changed from **white 30%** to **grays.200 solid**
- Disabled - the border is changed from **white 15%** to **grays.50 solid**

[Link](https://www.figma.com/file/0iCinYLqmAN5sbv305sw0C/branch/jnorUJk9Np9FhDqMYOxYjR/Button-Group?type=design&node-id=1%3A5&mode=design&t=bb0PsN6KMg9l89hY-1)

**Review by desig9stein — APPROVED** [review]

**Review by desig9stein — APPROVED** [review]

**Pull request merged**
