### PR TITLE
fix(gridToolbarHiding): columnsAreaMaxHeight input property

### LINKED ISSUE #10529: The columnsAreaMaxHeight input property of IgxGridToolbarHiding and IgxGridToolbarPinning is not working as expected
## Description  
The columnsAreaMaxHeight input property of IgxGridToolbarHiding and IgxGridToolbarPinning is not working as expected.

 * igniteui-angular version: 12.2.0
 * browser: any

## Steps to reproduce  

1. Open the following sample - [here](https://stackblitz.com/edit/github-a3pbhj?file=src%2Fapp%2Fgrid%2Fgrid-toolbar-sample%2Fgrid-toolbar-sample-2.component.html).
2. Open the dropdowns of IgxGridToolbarHiding and IgxGridToolbarPinning.

## Result  
The max height of the columns area in the dropdowns is not set.

## Expected result  
The max height of the columns area in the dropdowns should be set to 50px.

### PR DESCRIPTION
**Pull request by Volen99**
Closes #10529

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — CHANGES_REQUESTED** [review]
Please add documentation about this property and fix the test to test the actual height of the rendered element.

**Review by Svetloslav15 — APPROVED** [review]

**Comment by kdinev** [comment]
@Volen99 Test is failing.

**Comment by Volen99** [comment]
> Member



> @Volen99 Test is failing.

That is because this test was never working. It was only pushed so other people see what is wrong with it and try to fix it. This fix is without test, as I couldn't write one, matching a specific case.

**Comment by kdinev** [comment]
@hanastasov Who should be assigned to push a fix to this PR so the test passes?

**Comment by hanastasov** [comment]
> 

I am hands on it.

**Pull request merged**
