### PR TITLE
feat(igxGrid): Multi cell selection

### LINKED ISSUE #3915: Multi-cell selection
igxGrid multi-cell selection feature enables range selection of cells in the grid. This feature will be useful for highlighting of cell data and copying data to the Clipboard. 

- [x] [Specification](https://github.com/IgniteUI/igniteui-angular/wiki/igxGrid-Multi-cell-selection-Specification)
- [ ] Implementation
- [ ] [Tests](https://github.com/IgniteUI/igniteui-angular/issues/3794)
- [ ] Bug fixing
- [ ] Samples
- [ ] Documentation

### PR DESCRIPTION
**Pull request by rkaraivanov**
Closes #3915  
Related to #2903 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by gedinakova** [comment]
@rkaraivanov Currently, not all matching rows are shown when applying a filter after the grid was scrolled vertically.
#### Steps to reproduce: 
1. Load Grid Column Moving dev demo
2. Scroll the grid vertically to the middle
3. Open ESF UI for ContactTitle column
4. Select "Owner" only & apply the filter
5. Note the result

#### Actual result:
Only 2.5 rows are visible. No vertical scrollbar. 
image

#### Note: Not reproduced on master.

#### Expected result:
All 7 matching rows should be visible.

**Comment by gedinakova** [comment]
Selection range's row start & end are not updated after (un)grouping.
#### Steps to reproduce: 
1. Load Grid Column Moving dev demo
2. Group by 'CompanyName'
3. Scroll to the bottom
4. Select "FRANS" and "FRANK" cells > Selection range: [ { "rowStart": 51, "rowEnd": 53, "columnStart": 0, "columnEnd": 0 } ]
5. Ungroup & note the cells in the first column

#### Actual result:
None of the cells is selected anymore. The selection range still says [ { "rowStart": 51, "rowEnd": 53, "columnStart": 0, "columnEnd": 0 } ]. 

#### Expected result:
We should probably update the rowStart and rowEnd so the selection is not lost.

**Comment by rkaraivanov** [comment]
@gedinakova
Can you retest the filter/paging scenario as well as #3409

**Comment by gedinakova** [comment]
@rkaraivanov Fixed, but there is still a little issue after clearing the filter or going back to the first page, where some records at the bottom are not rendered before you scroll. 
image

**Pull request merged**
