### PR TITLE
feat(add-row): implementing context-free beginAddRow method #9675 - master

### LINKED ISSUE #9675: Add row at top of grid
## Question  
I'm replacing an old jquery ignite grid with a new igx one. In the old one, we added a new row at the top of the grid like this: 
image

In the new grid, I'm starting the adding of a new row with the following code:
```
var row = this.grid.getRowByIndex(0);
row.beginAddRow();
```
This however seems to add a new row below the first row, which look odd:
image

How do I add a new row at the top of the grid?

 * igniteui-angular version: 10.2

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #9675 #9429  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [x] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by skrustev** [comment]
Things I've found so far:

1. You can specify row index even if there is primary key set for the grid, which results in wrong row [here](https://github.com/IgniteUI/igniteui-angular/pull/10070/files#diff-440a9d274756495c7bb4e7acf64e5ff3757d060999c43e932fe7654b565f793eR5985) and throws warning. I think having a separate methods for specifying `index` or `rowID` will resolve this like we talked earlier about it.

2. You cannot use the API if there are no rows added for the similar case as 1, but here you have no rowID to base it off of and I think default behavior should be triggered in this case.

3. If the default behavior is changed like it is at the moment in the PR, [here](https://github.com/IgniteUI/igniteui-angular/pull/10070/files#diff-546e39078a4b678b1598e0e135010a8081b02f4f63bc9997650a08633caa5879L440) the second part of the shorthand if is obsolete and can be just `null`.

4. The API doesn't seem to work for IgxTreeGrid, since its calling `get_rec_index_by_id` for the base gridAPI service because it is in the base class and not the IgxTreeGrid one and also the dataView in the IgxTreeGrid is different and would need separate implementation. 

5.  A small note currently for the IgxTreeGrid is that you cannot show the Add Row at the top of an inner level inside the tree. I think its far from a limitation, but maybe in the context of the Tree Grid it might make sense.

**Comment by ChronosSF** [comment]
@skrustev , think I addressed your comments. Please, check the PR again.

**Review by MayaKirova — APPROVED** [review]
Looks good but decide what to do with the xit-ted test. Either remove it or maybe log a separate task to fix it.

**Comment by skrustev** [comment]
Other things from further testing:

1. Add row does not start when you pin a row and try to add a row at index 2 for example

**Comment by ChronosSF** [comment]
These are low impact as they involve row pinning. I'll log them separately.

**Review by skrustev — APPROVED** [review]

**Pull request merged**
