### PR TITLE
refactor(nav-drawer): Update material, fluent, and bootstrap themes

### LINKED ISSUE #14097: Align navdrawer implementation with UI kit designs
## Description  
There are a lot of misalignments between the implementation of the nav drawer and the designs in the Material, Bootstrap, and Fluent UI kits. They should be updated.

[Material Navdrawer](https://www.figma.com/file/rPQFTo4Ktj4tMDncnwPtHk/Indigo.Design-UI-Kit-for-Material-1.5?node-id=3264%3A193142&mode=dev)

[Bootstrap Navdrawer](https://www.figma.com/file/WSQv6uvWEcxOV8D5eDcKMY/Indigo.Design-UI-Kit-for-Bootstrap-1.5?node-id=5867%3A982&mode=dev)

[Fluent Navdrawer](https://www.figma.com/file/hHXKBpg1UhCMziIkdsYLFF/Indigo.Design-UI-Kit-for-Fluent-1.5?node-id=2453%3A63970&mode=dev)

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #14097

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by didimmova** [comment]
The navdrawer isn't getting animated on open

**Comment by sbayreva** [comment]
**Fluent**
1. The font family of the Header item should be Subtitle 1
2. The width of all items should be 240
3. The stroke of the component should be inside

**Comment by imincheva** [comment]
**Bootstrap**
- The header text isn't aligned to the center of the span

**Comment by sbayreva** [comment]
**Fluent**
 The font family of the Header item should be Subtitle 1 and should be aligned to the center of the span.

**Comment by sbayreva** [comment]
> **Fluent** The font family of the Header item should be Subtitle 1 and should be aligned to the center of the span.

The comment is applied. Everything looks good.

**Review by simeonoff — APPROVED** [review]

**Comment by AnjiManova** [comment]
Everything looks ok.

**Pull request closed without merging**
