### PR TITLE
feat(switch): refine switch theme

### LINKED ISSUE #14109: Switch component refinement
### Description
The Checkbox component in Material, Fluent and Bootstrap has been refined based on the official design systems.

**Material**
image visual reference in [Indigo.Design UI Kit for Material](https://www.figma.com/file/rPQFTo4Ktj4tMDncnwPtHk/Indigo.Design-UI-Kit-for-Material-1.5?type=design&node-id=3264%3A163058&mode=design&t=WTSNFLmr2vrhDju8-1)

**Fluent**
In Fluent, our improvements are more so treated the refinement as new visual stylisation and follow the [Indigo.Design UI Kit for Fluent](https://www.figma.com/file/hHXKBpg1UhCMziIkdsYLFF/Indigo.Design-UI-Kit-for-Fluent-1.5?type=design&node-id=3060%3A81855&mode=design&t=kkMOCWUp60pna75k-1) for reference.

**Bootstrap**
The case is the same in Bootstrap as in Fluent. Please follow the [Indigo.Design UI Kit for Bootstrap](https://www.figma.com/file/WSQv6uvWEcxOV8D5eDcKMY/Indigo.Design-UI-Kit-for-Bootstrap-1.5?type=design&node-id=6722%3A436&mode=design&t=NIYinLtdX7S1Y0us-1) for reference.

### PR DESCRIPTION
**Pull request by didimmova**
Closes #14109

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by desig9stein** [comment]
@didimmova

**Material**
There is an elevation 3 on the thumb on hover, I don't see it in the UI kit. Also, it is triggered upon hovering the thumb itself not the whole switch.

https://github.com/IgniteUI/igniteui-angular/assets/21260963/de16ed55-6726-4ee3-9167-2f6a0a227ca2

**Fluent** 
there is a problem with the keyboard focus
Screenshot 2024-04-26 at 7 09 09

**Bootstrap**
The outline with keyboard focus should be 4px

UI kit
Screenshot 2024-04-26 at 7 16 06

Implementation
Screenshot 2024-04-26 at 7 16 18

**Comment by didimmova** [comment]
> @didimmova
> 
> **Material** There is an elevation 3 on the thumb on hover, I don't see it in the UI kit. Also, it is triggered upon hovering the thumb itself not the whole switch.
> 
>  Screen.Recording.2024-04-26.at.7.00.21.mov 
> **Fluent** there is a problem with the keyboard focus Screenshot 2024-04-26 at 7 09 09
> 
> **Bootstrap** The outline with keyboard focus should be 4px
> 
> UI kit Screenshot 2024-04-26 at 7 16 06
> 
> Implementation Screenshot 2024-04-26 at 7 16 18

I fixed the bootstrap and fluent ones. About the material one, the shadow is elevation-1 in all states, so it's static (meaning it doesn't change on hover, so it doesn't matter where you hover) but even if it wasn't, according to the design team, it should be on the thumb, because that's the element you're interacting with and the shadow, changing lies under it.

**Comment by AnjiManova** [comment]
**Material**

All requested changes are applied correctly. ✅ 
The "pressed" states have been changed for both themes (Light and Dark):
- The "**Checked**" switch will use for "pressed" the **thumb-on** color
- The "**Unchecked**" switch will use for "pressed" the **track-on** color

**Comment by imincheva** [comment]
**Bootstrap**
All looks good and by design!

**Comment by AnjiManova** [comment]
**Fluent**

Only one comment related to the Focus Border size:
- currently, the focus border size value is **-(0.125)**
image

and it should be **-(0.1875)**
image

**Comment by AnjiManova** [comment]
**Fluent**

Based on the WebC validations, something came out. In addition, the thumb isn't positioned correctly. It should have a 3px margin instead of 4px.

**Pull request merged**
