### PR TITLE
fix(expansion-panel): ensure disabled header is not tabbable

### LINKED ISSUE #9606: [IgxExpansionPanel] - `disabled` panel header has tabIndex=0
## Description  
Settings the `IgxExpansionPanelHeaderComponent.disabled` input to `true` disables user interaction w/ the header (click/ keyboard expand), but the header is still accessible via `(Shift +) Tab` navigation, as the `igx-expansion-panel-header` inner div has a strict tabIndex of `0`.

Disabling the panel header should set the tab index to -1 (behavioral change) OR the header should expose and input for controlling its tabIndex (defaulting to 0)

 * igniteui-angular version: ALL
 * browser: N/A

## Steps to reproduce  

1. Open the follwoing [stackblitz](https://stackblitz.com/edit/expansion-panel-header-disabled?file=src/app/expansion-sample-4/expansion-sample-4.component.html)
2. Click on the first panel (HTML5)
3. Hit `Tab`

## Result  
The focus moves to the second (disabled) panel header (CSS)

## Expected result  
The focus moves to the third (!disabled) panel header (SASS/SCSS)

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #9606

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by Lipata — APPROVED** [review]

**Comment by kdinev** [comment]
Shouldn't this fix also make it in prior versions in order to be released with a patch?

**Comment by ViktorSlavov** [comment]
@kdinev 
I'm hesitant to add this to prior versions as it introduces a behavioral change and the trigger for this change was the implementation of the igx-accordion.
If you think it's okay to add it to prior patch versions despite the change, I'll make the PRs 👍

**Comment by kdinev** [comment]
@ViktorSlavov The issue is marked as a bug, so I assumed it's a bug fix.

**Comment by ViktorSlavov** [comment]
@kdinev 
Yeah, you're right. And, considering the use case that the behavioral change would hit is such a narrow one, it shouldn't be a problem to introduce it in prior version - I've made the PRs and will add the labels to the issue

**Pull request merged**
