### PR TITLE
fix(grid): fix grid cells are not aligned with the column headers

### LINKED ISSUE #4161: Grid cells are not aligned with the column headers when grouping is applied
## Description  
Grid cells are not aligned with the column headers when grouping is applied.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Open the 'Data Grid' -> 'Group By' topic  on staging environment.
2. Look at the demo.

## Result  
The cells are not aligned with the column headers.

## Expected result  
The cells should be aligned with the column headers.

## Attachments  
image

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #4161   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by mpavlinov** [comment]
@DiyanDimitrov Please test for displayDensity `cosy` and `compact`.

**Comment by DiyanDimitrov** [comment]
If you open the 'Hierarchical Grid' dev demo, now the summaries are not aligned:

image

**Comment by skrustev** [comment]
> If you open the 'Hierarchical Grid' dev demo, now the summaries are not aligned:

That is why currently there is a failing test as well.

**Comment by DiyanDimitrov** [comment]
It works for 'compact' and 'comfortable', but there are few pixels misalignment with 'cosy'.

**Pull request merged**
