### PR TITLE
fix(grid-summaries): fix summaries width

### LINKED ISSUE #1050: Summaries incorrect width
### Description  
Summaries won't work if there is no fixed width on the columns.

### Steps to reproduce  

1. Open grid-summary demo
2. Make some of the columns fixed width but not all of them

### Result  
The summaries column width is incorrect

### Expected result  
The summaries column width should be the same as the grid body cells and grid header cells

### Attachments  
screenshot-2018-4-18 igniteui for angular samples

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #1050 

Additional information related to this pull request:

### CODE REVIEW

**Comment by sstoyanovIG** [comment]
Closes #1008

**Comment by desig9stein** [comment]
My changes will work when #1049 gets merged

**Comment by zdrawku** [comment]
@desig9stein #1049 is merged now, can we test this PR now?

**Comment by sstoyanovIG** [comment]
Everything looks good except when we have a long summary result. The text is not truncated and the whole summary becomes wider than the cell. @desig9stein is working in this.

**Pull request merged**
