### PR TITLE
feat(esf): improve search results accessibility - 16.1.x

### LINKED ISSUE #13524: [Screen Reader] Screen reader does not announce search results information by entering 'valid/invalid' data under 'Name' dialog.
Screen reader users rely on auditory feedback to understand the outcome of their actions. If search results are not announced, users won't know whether their search query was successful or if there were any relevant matches.

Screen reader does not announce search results information by entering 'valid/invalid' data under 'Name' dialog.
NVDA remain silent.

Expected Result:

Screen reader should announce search results information by entering 'valid/invalid' data under 'Name' dialog.

source link: [Excel Style Filtering in Angular Data Grid- Ignite UI for Angular (infragistics.com)](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering)

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #13524 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ChronosSF** [comment]
LGTM, though since the previous implementation is very non-accessible, I think we can safely add this to all supported versions, not just 17.0

I am also unsure... maybe when we make NVDA say how many matches there are, we should only include the actual matches and not the Select All / Add to Selection checkboxes as while they are in the UI, they are not exactly matching the search.

@sdimchevski , @kdinev , do you have comments about that?

**Comment by ChronosSF** [comment]
@onlyexeption , speaking about this with @rkaraivanov and @damyanpetev , we decided that the choice of approach would need some further research. I'll freeze the PR for the time being and revisit it next sprint most likely.

**Comment by ChronosSF** [comment]
@onlyexeption , @igdmdimitrov , to continue with this item please research for accessibility patterns and specs around search fields.

**Comment by onlyexeption** [comment]
@damyanpetev, @rkaraivanov, after conducting a little research going through popular websites and applications with the NVDA reader, I've found out that the only websites (out of many) where search results were announced, are using the same approach with a hidden div that updates dynamically. Screenshots are attached for reference. LMK what you think.

image
⠀
⠀
⠀
image
⠀
⠀
⠀
image
⠀
⠀
⠀
image

**Comment by ChronosSF** [comment]
We discussed this today again with @damyanpetev and decided that the approach is okay, as long as you change it to polite from assertive and localize the message. The localization should also allow for changing the position of the number and other words within. So basically for English it should be something like ```{num} matches.``` and then you will replace the result in the template.

**Review by ChronosSF — DISMISSED** [review]

**Review by ChronosSF — APPROVED** [review]

**Pull request merged**
