### PR TITLE
Refactor input type border

### LINKED ISSUE #4535: Wrong label position for input with type "Border"
## Description  
According material.io the labels for input types "border" must not be inside the input, they should be at the middle of the border. 

You may see material-component implementation [here](https://material-components.github.io/material-components-web-catalog/#/component/select) (see the outlined demo).

 * igniteui-angular version: ^7.2.4
 * browser: Chrome

## Steps to reproduce  

1. Open your demo [here](https://stackblitz.com/angular/keropxgornk)
2. Go to the input named with "Border Type" and write some value...

## Result  
The label is moved at position -50% and scaled to 75%, like this:
image

## Expected result  
Label should be positioned at the middle of the border like this:
image

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #4535

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by StefanIvanov** [comment]
@wnvko will help with the failing test

**Comment by StefanIvanov** [comment]
@simeonoff can you make another review now that all checks are passing and the tests are fixed

**Comment by ddincheva** [comment]
During the test, I found the following problems:
When there is no value in the input and modify its value though API the border is overlapping the label:
image
In IE11 the label is cut if there is no value in the input:
image
There is double border when display density is compact: 
image
Compare to cosy:
image

If hide or show the labels run time, the border is not correct:
image
image

**Comment by desig9stein** [comment]
@ddincheva I am working on all the issues you found

**Comment by simeonoff** [comment]
@desig9stein I think we should leave this on the back burner for now. There are simply too many issues that arise from implementing the request using this approach. Let's focus our efforts on something else for now.

**Comment by kdinev** [comment]
@simeonoff Should I delete the branch?

**Pull request closed without merging**
