### PR TITLE
Fix simple dimensions merging on same level when there are multiple siblings.

### LINKED ISSUE #10546: [igxPivot] With 2 dimensions with no children generates incorrect rows.
## Description  
When setting 2 dimensions with no children, data is not grouped correctly.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Set 2 dimensions with no children:
```
 rows: [
            {
                memberName: 'ProductCategory',
                enabled: true
            },
            {
                memberName: 'SellerName',
                enabled: true
            }
        ],
```

## Result  
Observe the result:

image

Some records are missing here. There should be 3 records for Clothing and 2 for Components.

## Expected result  
Data should be correctly generated.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### LINKED ISSUE #10606: [igxPivot] Rows after 1st group have missing records when one of the dimensions have hierarchy.
## Description  

When the middle dimension has hierarchy, all groups after the first one have missing records.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run the pivot-hierarchy sample with the following config:

```
rows: [{
            memberName: 'Seller',
            memberFunction: (data) => data.Seller.Name,
            enabled: true,
        },
        {
            memberName: 'All',
            memberFunction: () => 'All',
            enabled: true,
            childLevel:
            {

                memberName: 'Product',
                memberFunction: (data) => data.Product.Name,
                enabled: true

            }
        },
        {
            memberName: 'City',
            memberFunction: (data) => data.Seller.City,
            enabled: true,
        },
        ],
```

2. Scroll down to the second group for seller - 'Benjamin Meekins'

## Result  
Some records are missing.

image

image

## Expected result  
Here instead of 1 record with City, there should be multiple (20 for 'All', 4 for 'Accessories', 5 for 'Clothing', 6 for 'Bikes', 5 for 'Components').

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by skrustev**
Closes #10546 
Closes #10606

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
If one of the dimensions has hierarchy, for example:

```
  rows: [
            {
                enabled: true,
                memberName: "AllProd",
                memberFunction: (rec) => 'AllProd',
                childLevel: {
                    memberName: 'ProductCategory',
                    enabled: true
                }
            },
            {
                enabled: true,
                memberName: 'Date'
            }
        ]
```

The data is not ordered correctly:

image

The 'AllProd' rows should be the first and then the specific product rows.

**Comment by MayaKirova** [comment]
The check in the nested hierarchy processing (processSubGroups) should also be updated, since when there's a hierarchy (childLevel) followed by a row with no hierarchy some records seems to be missing from the final data:

image

image

Here instead of 1 record with City, there should be multiple (20 for 'All', 4 for 'Accessories', 5 for 'Clothing', 6 for 'Bikes', 5 for 'Components').

**Comment by MayaKirova** [comment]
I've logged the last issue separately at: https://github.com/IgniteUI/igniteui-angular/issues/10606

**Review by mddragnev — APPROVED** [review]

**Comment by MayaKirova** [comment]
Regarding #10606 there still seem to be some missing records:

image

But now only for the even Seller records (  2 - Benjamin Meekins, 4 - David Haley, 6 - Harry Tyler etc.)

There are also some weird records with object values that appear in some records:

image

**Pull request merged**
