### PR TITLE
fix(igxGrid): Grid should render all columns when grid width is set to null.

### LINKED ISSUE #5288: Grid width set to `null` is not rendering grid columns at all.
## Description  
Setting grid with to `null` does not render columns at all making the grid empty and that is why rows render as 1px in height.
The same is for Tree Grid and Hierarchical Grid.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Open the "gridColumnResizing" demo sample
2. Set the width of the grid to `null`.
3. Observe the rendered grid.

## Result  
The grid is not rendering any columns.

## Expected result  
The grid should render all columns in the grid without horizontal virtualization. If there is vertical virtualization it should not be affected.

## Attachments  
width-null

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #5288  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by 3phase** [comment]
When setting igx-grid's width property to null, space is being added. That bug doesn't persist below 8.0.x and in case width is set to a value, for instance 100%, as well.
The bug fixes itself automatically when a column resize is made.

**Comment by MayaKirova** [comment]
@3phase Please re-test.

**Comment by 3phase** [comment]
**The bug persists w/ versions 8.0.x and above.**
The tested samples are Grid Filter Template and Grid Column Resizing.
The first tested sample breaks on the last column and appends space for almost one full-size column at the end. When one attempts to resize a random column, the breaks are getting fixed and the behavior is as expected.
The second tested sample adds y-scrollbar but on resize hides it.
I'm attaching screenshots of both samples while broken.

**Grid Filter Template:**
image

**Grid Column Resize:**
image

**Comment by MayaKirova** [comment]
@3phase Please re-test again :)

**Comment by ChronosSF** [comment]
Check the comments in https://github.com/IgniteUI/igniteui-angular/pull/5396

**Comment by ChronosSF** [comment]
New set of issues (again just use width: null in the sample code)

- [ ] CellEditing sample - no content is shown in the cells
- [ ] MCH sample - (first remove the section tag as it hides the extra width) - hide/showing a group through the button click requires an additional click on the grid to detect the change 
    - *same happens in the pinning sample when using the button to hide a column*
- [ ] Resizing sample - when you resize a column the background of the horizontal scrollbar shows and never hides
- [ ] Filter template sample - only when you resize a column are summaries shown (they should be shown by default)
- [ ] GroupBy sample - horizontal scrollbar background is visible but the scrollbar is not
    - *same thing happens in the first treegrid sample*
- [ ] Percentage sample - there is empty area to the right of the columns
- [ ] Row drag sample - enabling/disabling the drag column multiple times slowly expands the grid in width
- [ ] Grid Selection sample - the grid renders a horizontal scrollbar for some reason
- [ ] Grid Summaries sample - the vertical scrollbar is not shown and the grid cannot be scrolled down even though there are more records than the viewport can display

**Comment by MayaKirova** [comment]
@ChronosSF 
-  CellEditing sample - Content renders fine for me when width is set to null => [width]="null".

Are you perhaps setting "null" as string and not as a value, for example width='null'? Please note that in that case the resolved value will be string and we do no have explicit covertion for such scenarios.

**Comment by ChronosSF** [comment]
Agree about 1. - probably didn't box the width input.

1. 
Capture

```html
    <igx-grid #grid1 [data]="remote | async" [primaryKey]="'ProductID'"
            [rowSelectable]="selection" (onSelection)="handleRowSelection($event)"
            [width]="null" [height]="'600px'">
        <igx-column [field]="'ProductID'" [editable]="true" [width]="'80%'"></igx-column>
        <igx-column [field]="'ProductName'"></igx-column>
        <igx-column [field]="'UnitsInStock'"></igx-column>
    </igx-grid>
```

2. 
Capture1

```html
<div class="sample-content">
    <div class="sample-column">
        <igx-grid [allowFiltering]="true" [data]="data" [autoGenerate]="false" displayDensity="comfortable" [width]="null" height="600px" [paging]="true" [perPage]="10">
            <igx-column field="ProductName" [pinned]="true" [movable]="true" header="Product Name" width="19%" [dataType]="'string'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
            </igx-column>
            <igx-column field="UnitsInStock" [pinned]="false" [movable]="true"  header="Units In Stock" width="19%" [dataType]="'number'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
            </igx-column>
            <igx-column field="OrderDate" [movable]="true" header="Order Date" width="19%" [dataType]="'date'" [sortable]="true" [hasSummary]="false" [editable]="true" [filterable]="true" [resizable]="true">
                <ng-template igxCell let-cell="cell" let-val>
                    {{val | date:'dd/MM/yyyy'}}
                </ng-template>
            </igx-column>
            <igx-column field="Discontinued" [movable]="true" [resizable]="true"  header="Discontinued" width="15%" [dataType]="'boolean'" [sortable]="false" [hasSummary]="false" [editable]="true" [filterable]="false" [resizable]="true">
            </igx-column>
            <igx-column field="ReorderLevel" header="Reorder Level" [movable]="true" [resizable]="true" [dataType]="'number'" width="19%" [sortable]="false" [hasSummary]="false" [editable]="true" >
                <ng-template igxCellEditor let-cell="cell">
                    <input type="number" [(ngModel)]="cell.value" style="color: black"/>
                </ng-template>
            </igx-column>
        </igx-grid>
    </div>
</div>
```

**Pull request merged**
