### PR TITLE
Indigo Themes: Update List, Progress, and Dropdown

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by sbayreva** [comment]
**Linear bar** 

1. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2

**Circular Progress**

1. The component size should be 48px
2. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2

**Comment by AnjiManova** [comment]
**Dropdown**

everything looks fine to me

**Comment by imincheva** [comment]
**List**
- Header text color variable is set correctly, but seems to be disabled or something.
image

- The height of the header text should be 16px (the line-height should be overriden)
- The background on hover should have 4px border radius
- 2px gap between title and subtitle is missing
- The pink ripple on click is very odd IMO, but since there's no design @andiesm813 should confirm whether this is the appropriate behaviour
- The paddings on the list header and items in cosy and compact should be validated by @andiesm813 as well, since we don't support sizing for the list yet.
- --item-text-color-hover should be grays.900 in light mode
- --item-subtitle-color-hover should be grays.700 in light mode
- --item-action-color-hover should be grays.700 in light mode
- --item-text-color should be white 80% in dark mode
- --item-background-hover should be primary.400 30% opacity in dark mode

**Comment by andiesm813** [comment]
> **List**
> 
> * Header text color variable is set correctly, but seems to be disabled or something.
> 
> image
> * The height of the header text should be 16px (the line-height should be overriden)
> * The background on hover should have 4px border radius
> * 2px gap between title and subtitle is missing
> * The pink ripple on click is very odd IMO, but since there's no design @andiesm813 should confirm whether this is the appropriate behaviour
> * The paddings on the list header and items in large and small should be validated by @andiesm813 as well, since we don't support sizing for the list yet.
> * The correct paddings on the header and list items for medium are 6px 12px
> * --item-text-color-hover should be grays.900 in light mode
> * --item-subtitle-color-hover should be grays.700 in light mode
> * --item-action-color-hover should be grays.700 in light mode
> * --item-text-color should be white 80% in dark mode
> * --item-background-hover should be primary.400 30% opacity in dark mode

One of the issues listed "item text color" in dark mode, was incorrect in the Figma. I just fixed it in [this branch](https://www.figma.com/design/dkGpSYipbp68uZ1VpRfmsJ/branch/cMlfX2vFuCkozRMexeGuAZ/Indigo.Design-UI-Kit-for-Indigo-1.5-Workfile?m=auto&t=v2bG8HXFvEV2SKe3-1).
The expected item-text-color in DARK mode would be white 90%

**Comment by andiesm813** [comment]
> **Linear bar**
> 
> 1. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2
> 
> **Circular Progress**
> 
> 1. The component size should be 48px
> 2. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2

Yes! those are the only 2 issues i saw too. Correct font style would be **Subtitle 2** and the issue with the circular progress size.

**Comment by andiesm813** [comment]
**DROPDOWN**
All looks good to me too. ✅

**Comment by andiesm813** [comment]
### **List**
Besides the comments made by @imincheva , which are all right on, i'm adding more comments:

**LIGHT THEME**

--header-text-color has the correct value in the CSS, however, in the samples, the header seems way darker than grays600. It looks almost as dark as grays900.



**GENERAL (applies to light and dark)**

There should no ripple effect on click. No other components (that i noticed) in Indigo theme have it.... There should be no ripple effect for any of the components in the Indigo theme. As an example, navdrawer (which is also a list), doesn't have ripple effect on click.


**SIZES**
The implemented sizes are incorrect. All the sizes that are implemented for COMFORTABLE correspond to COSY. And the ones implemented for COSY correspond to COMPACT. So the sizes for LARGE need to be defined by me. See below.
These sizes specified below are consistent with the sizes of the TREE component.

Comfy - Large

- The height of the header container should be 32px. 
- The height of the single line item should be 32px. 
- List Item inner paddings: 8px 16px.

Cosy - Medium

- The height of the header container should be 28px. 
- The height of the single line item should be 28px. 
- List Item inner paddings: 6px 12px.

Compact - Small

- The height of the header container should be 24px. 
- The height of the single line item should be 24px. 
- List Item inner paddings: 4px 8px.

**Comment by simeonoff** [comment]
> ### **List**
> Besides the comments made by @imincheva , which are all right on, i'm adding more comments:
> 
> **LIGHT THEME**
> 
> --header-text-color has the correct value in the CSS, however, in the samples, the header seems way darker than grays600. It looks almost as dark as grays900.
> 
> **GENERAL (applies to light and dark)**
> 
> There should no ripple effect on click. No other components (that i noticed) in Indigo theme have it.... There should be no ripple effect for any of the components in the Indigo theme. As an example, navdrawer (which is also a list), doesn't have ripple effect on click.
> 
> **SIZES** The implemented sizes are incorrect. All the sizes that are implemented for COMFORTABLE correspond to COSY. And the ones implemented for COSY correspond to COMPACT. So the sizes for LARGE need to be defined by me. See below. These sizes specified below are consistent with the sizes of the TREE component.
> 
> Comfy - Large
> 
> * The height of the header container should be 32px.
> * The height of the single line item should be 32px.
> * List Item inner paddings: 8px 16px.
> 
> Cosy - Medium
> 
> * The height of the header container should be 28px.
> * The height of the single line item should be 28px.
> * List Item inner paddings: 6px 12px.
> 
> Compact - Small
> 
> * The height of the header container should be 24px.
> * The height of the single line item should be 24px.
> * List Item inner paddings: 4px 8px.

@desig9stein

**Comment by imincheva** [comment]
**List**
The following comments haven't been fixed: 
- The background on hover should have 4px border radius
- --item-text-color-hover should be grays.900 in light mode

**Comment by SisIvanova** [comment]
> > **Linear bar**
> > 
> > 1. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2
> > 
> > **Circular Progress**
> > 
> > 1. The component size should be 48px
> > 2. The font that is used is correct but I am not sure whether it is used as a style - it should be Subtitle 2
> 
> Yes! those are the only 2 issues i saw too. Correct font style would be **Subtitle 2** and the issue with the circular progress size.

We will create typography for the two components in a separate PR since this will introduce changes in all themes. The new issue is already created - https://github.com/IgniteUI/igniteui-angular/issues/14350

**Review by SisIvanova — DISMISSED** [review]

**Pull request merged**
