### PR TITLE
fix(igxGrid): Wait for zone onStable to ensure view is updated and ro…

### LINKED ISSUE #6206: Expanding a row and then scrolling to the bottom right and then returning to the row and collapsing it results in scrolled next row.
## Description  
Expanding a row and then scrolling to the bottom right and then returning to the row and collapsing it results in scrolled next row.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

1. Open Grid Master-Detail in the sample browser and add more columns.
2. Expand the first row.
3. Scroll to the bottom right edge of the grid.
4. Scroll back to the start of the grid.
5. Collapse the first row.

## Result  
The second row appear as if it scrolled to the far right.

## Expected result  
The second row should not appear as if it scrolled to the far right.

## Attachments  
MasterDetailScrollCollapse

### LINKED ISSUE #6248: When grid is scrolled horizontal and scroll vertical the row layout is not correct
## Description  
When grid is scrolled horizontal and scroll vertical the row layout is not correct

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Group by column 'ConatctTitle'
3. Scroll vertical
4. Scroll horizontal
5. Scroll vertical
6. Scroll horizontal

Note: Same is reproducible in hgrid when a row is expanded and also with master details and in the tree grid with child summaries

## Result  
In the rows cells are misaligned

## Expected result  
Rows content should be correct

## Attachments  
scroll

### PR DESCRIPTION
**Pull request by MayaKirova**
…w is available.

Closes #6206   
Closes #6248

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by nrobakova** [comment]
Hi @MayaKirova ,
I tested this PR. the base scenarios with scroll are fixed, but now the navigation with the keyboard is not correct:
Steps to reproduce:
 1. Edit dev sample  gridMasterDetail and change columns to:
` this.columns = [
            { dataType: 'string', field: 'ContactName', width: 200 },
            { dataType: 'string', field: 'CompanyName', width: 300 },
            { dataType: 'string', field: 'Salary', width: 300 },
            { dataType: 'string', field: 'ContactTitle', width: 200 },
            { dataType: 'string', field: 'Address', width: 300 },
            { dataType: 'string', field: 'City', width: 300 }
        ];`
2. Group by columns City.
3. Click on a cell and press Ctrl+End
4. Press Ctrl+home

Not correct cell is selected and the row layout is broken.

**Comment by MayaKirova** [comment]
@nrobakova I can reproduce the same in master. It does not appear to be related to this particular fix and should be logged separately.

**Comment by ChronosSF** [comment]
@nrobakova , if you agree we can log this separately as it is not related to this issue only.

**Comment by nrobakova** [comment]
I reported a bug for the described issue. #6315.

**Pull request merged**
