### PR TITLE
fix(column-selection): allow to copy column values-master #8819

### LINKED ISSUE #8819: igx-grid column selection does not allow me to copy column values
## Description  
I have a grid with column selection and upon Ctrl+C on the selected column/s, I expect column values to be added to the clipboard.

 * igniteui-angular version: 11.0.11
 * browser: all

## Steps to reproduce  

1. Define a grid with `columnSelection`
2. Select a column
3. Ctrl+C

## Result  
Clipboard is empty.

## Expected result  
Clipboard should contain the column values.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #8819 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ddincheva** [comment]
Hello... I performed further testing and the copied data is still not correct
1. Go to gridColumnMoving dev sample
2. Select the column 'CompanyName'
3. Scroll the grid to the bottom and drag-select a range - last 3 rows from the column 'PostalCode' to the column 'CompanyName'
Screenshot_17

4. Copy the selected data and paste it somewhere 
Result: the selected data is not correctly arranged  and also repating values are added in the column CompanyName

Screenshot_16

**Comment by ddincheva** [comment]
In the following case an error is thrown: 
CopyMCH

**Comment by ddincheva** [comment]
When we have more than one selected range and a selected column only the column values and the lastly selected range are copied:
CopyMoreRanges

**Review by zdrawku — COMMENTED** [review]
Remove the redundant code that is commented out and also address the lint errors like "'event' is defined but never used"  within the files where your changes are

**Review by zdrawku — APPROVED** [review]

**Pull request merged**
