### PR TITLE
Introduce PivotGridRecord  interface for strongly typed record data related to pivot operations.

### LINKED ISSUE #10923: [igxPivot] Explore options for introducing a typed PivotGridRecord
Based on the PR review.

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #10923  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
@ChronosSF, @rkaraivanov As this pop out from the review, please check out the PivotRecord interface and share your opinion on it - https://github.com/IgniteUI/igniteui-angular/pull/10971/files#diff-c0103fd9016c198b1e34b57699b37f16b4d16138da6d6c9c01f4caf8639a723aR189

When we agree on it we'll have the green light to proceed on refactoring the tests.

**Review by ChronosSF — DISMISSED** [review]

**Comment by ChronosSF** [comment]
LGTM

**Review by ChronosSF — APPROVED** [review]

**Review by rkaraivanov — DISMISSED** [review]

**Comment by 3phase** [comment]
@MayaKirova
There's an issue when you collapse a column dimension and then apply filtering to a row dimension - the column dimension seems to expand again, although no need to.

pivot-issue-6

Additionally, there're conflicts with master.

**Comment by dkamburov** [comment]
@MayaKirova please resolve conflicts

**Review by dkamburov — APPROVED** [review]

**Comment by MayaKirova** [comment]
@3phase The issue no longer reproduces with the latest merge from master.

**Comment by 3phase** [comment]
I confirm that the above issue is not reproducible anymore.
The PR looks good to me.

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
