### PR TITLE
Pivot horizontal excel export

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes https://github.com/IgniteUI/igniteui-angular/issues/14470  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by skrustev** [comment]
I think there seem to be an issue if there are horizontally merged cells, for example when collapsed the other after that appear misaligned.

**Comment by MayaKirova** [comment]
> I think there seem to be an issue if there are horizontally merged cells, for example when collapsed the other after that appear misaligned.

Should be fixed now.

**Comment by skrustev** [comment]
There seem to be another issue with the generated structure for the excel file that wasn't present before when exporting the Pivot Grid State Persistence sample, without any modifications (I probably shouldn't leave it like that but i'll change it in the main pr)

**Comment by MayaKirova** [comment]
> There seem to be another issue with the generated structure for the excel file that wasn't present before when exporting the Pivot Grid State Persistence sample, without any modifications (I probably shouldn't leave it like that but i'll change the sample in the main pr)
> 
> image

Issue should be fixed now.

**Comment by skrustev** [comment]
I am still noticing unmerged cells in the case for the Pivot Grid State sample. Maybe when they are not on first row, when `USA` is collapsed for example:
image
image

**Review by skrustev — DISMISSED** [review]

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
