### PR TITLE
Updated Column Formatter API doc

### PR DESCRIPTION
**Pull request by brianlagunas**
Updated the Column Formatter API doc description to better illustrate the use case in which the formatter should be used.  A short code snippet has also been provided to show customers how they can implement their own formatters.

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [x] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by kdinev** [comment]
@brianlagunas There's a lint error with the max line length.

**Comment by brianlagunas** [comment]
Does it say which line?

**Comment by kdinev** [comment]
> ERROR: projects/igniteui-angular/src/lib/grids/column.component.ts:391:1 - Exceeds maximum line length of 140
> ERROR: projects/igniteui-angular/src/lib/grids/column.component.ts:392:1 - Exceeds maximum line length of 140
> ERROR: projects/igniteui-angular/src/lib/grids/column.component.ts:399:7 - trailing whitespace

**Comment by brianlagunas** [comment]
Hmm... seems it keeps failing on the linter rule. Why is that rule in place? Is this a limitation of Typedoc or is this a self-imposed limit?

**Comment by kdinev** [comment]
@brianlagunas The only error left is a trailing white space:

> ERROR: projects/igniteui-angular/src/lib/grids/column.component.ts:391:99 - trailing whitespace

**Comment by kdinev** [comment]
@brianlagunas I fixed it for you ;)

**Pull request merged**
