### PR TITLE
refactor(slider): update to match the latest material spec

### LINKED ISSUE #4542: igx-slider update to match latest material guidelines
## Is your feature request related to a problem? Please describe.
The current implementation and style of the igx-slider is not up to date with the latest [material guidelines](https://material.io/design/components/sliders.html#discrete-slider) for a slider component

## Describe the solution you'd like
Update spec and igx-slider to support ripple, new label balloon shape, behaviors that match the different states in the material guidelines.

### LINKED ISSUE #5219: When change slider input continuous to true the ticks are still previewed
## Description  
When change slider input continuous to true the ticks are still previewed

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample slider
2. For the first slider change input continuous to true

Note: same is valid when change continuous from true to false (ticks are not previewed)

## Result  
The slider has ticks

## Expected result  
As the slider is continuous the ticks should not be previewed 

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### LINKED ISSUE #5229: When change slider step the ticks are not updated
## Description  
When change slider step the ticks are not updated

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample slider
2. Change step on the first slider
3. Start changing the value with mouse dragging

## Result  
After point 2 ticks are not updated and when move slider it is flickering

## Expected result  
Slider ticks should be updated

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #4542
Closes #5219
Closes #5229

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD
 - [x] Refactor

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by nrobakova** [comment]
@simeonoff  and @Aleksandyr 
I have some issues:

1. When slider has steps the thump is not in correct position:
 image

2. When slider type is range and start moving a thump the both thumps are activated:
image

3. In IE11 when slider type is slider and click on the thump the label is not opened. It opens on the  next click.

**Comment by Aleksandyr** [comment]
@simeonoff Could you please consider adding a new class that will help to diversify the moment when the label and the ripple are visible.

**Comment by nrobakova** [comment]
Now when starts changing slider value and move with the mouse outside the slider the labels are closed.

**Comment by Aleksandyr** [comment]
> * [x]  Now when starts changing slider value and move with the mouse outside the slider the labels are closed.

@nrobakova Please proceed with the verification again. The above issue was resolved as well as #5229

**Comment by Aleksandyr** [comment]
With the current implementation, we are exposing one regression and some tests that are failing due to not fully cleared obstacles:
1. Regression is connected with mobile devices. You are unable to interact/slider properly.
2. As for the tests. With the current implementation, there are some pointer event handlers and pan gestures that are not clear how exactly they could be simulated.

**Comment by zdrawku** [comment]
@Aleksandyr Please make the same PR to master as well

**Pull request merged**
