### PR TITLE
Implement excel-style tree view in pivot grid.

### LINKED ISSUE #11049: [Pivot] Integrate ESF in tree view

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #11049  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
Some of the values of the noop sample are not populated
image

**Comment by MayaKirova** [comment]
@dkamburov Should show empty item now in case noop strategies are used (same as in master).

**Comment by mddragnev** [comment]
@MayaKirova When applying initial filtering from pivot configuration to a dimension which have hierarchy, all other values in the ESF are not present.
For example: Setting this dimension in the pivot dev sample
```
 {
            memberFunction: () => 'All',
            memberName: 'AllProducts',
            enabled: true,
            width: '25%',
            childLevel: {
                memberFunction: (data) => data.ProductCategory,
                memberName: 'ProductCategory',
                enabled: true,
                filter: this.filterExpTree
            }
        },
```
And this filtering expression tree
```
this.filterExpTree.filteringOperands = [
            {
                condition: IgxStringFilteringOperand.instance().condition('equals'),
                fieldName: 'ProductCategory',
                searchVal: 'Clothing'
            }
        ];
```

image

**Comment by MayaKirova** [comment]
@mddragnev For the hierarchical filters, there's a slightly different format for the search values. They  have to contain the full path to the child values that are included:
For example:
```
 this.filterExpTree.filteringOperands = [
            {
                condition: IgxStringFilteringOperand.instance().condition('equals'),
                fieldName: 'AllProducts',
                searchVal: "[All].[Clothing]"
            }, 
           {...}
        ];
```
And they need to be applied to the root:

```
{
            memberFunction: () => 'All',
            memberName: 'AllProducts',
            filter: this.filterExpTree,
            enabled: true,
            width: '25%',
            childLevel: {
                memberFunction: (data) => data.ProductCategory,
                memberName: 'ProductCategory',
                enabled: true
            }
        }
```

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
