### PR TITLE
fix(grid): Adding active styles for summaries, group row and header

### LINKED ISSUE #7142: Grid active element styling
## Description  
Except for the header, cell, summary cell (and “selected” equivalents) active element style should be applicable also to:

1.	Column headers with collapsible column groups
2.	Grouped row
3.	Master detail view 
4.	Active styling on “tab stop” element? @Stefan, this is something that should be considered as well. Currently we do not have active element indication for the tab stops (except the thin blue line, which is browser default from Chrome).

Proposed design by @StefanIvanov :
“I am adding designs based on the approach we use for body cell activation"

With border:
image

Without border:
image

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #7142

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by zdrawku** [comment]
master rebase

**Comment by ddincheva** [comment]
@desig9stein , is this styling on expand/ collapse indicator by design?!
image

**Comment by desig9stein** [comment]
> @desig9stein , is this styling on expand/ collapse indicator by design?!
> image

No, I will check.

**Comment by ddincheva** [comment]
Well Done :)

**Pull request merged**
