### PR TITLE
fix(igxGrid): Set changeDetection for cell component to onPush.

### LINKED ISSUE #1923: Grid Keyboard navigation performance issue
### Description  
When you open the Propeller Grid and you select a cell and hold the right arrow key to start navigation the scroll is lagging. 

### Steps to reproduce  

1. Open Staging
2. Scroll the Grid with the keyboard
3. ...

### Result  
There is a lag on scrolling

### Expected result  
There should be no lag

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #1923.

Note: Please also test if change detection on cells works as expected (for example with editing).

### CODE REVIEW

**Comment by MayaKirova** [comment]
@zdrawku Could you elaborate on the scenarios you feel are not fixed?

**Comment by zdrawku** [comment]
@rkaraivanov is currently working on this issue as well, he will share with you a possible fix

**Comment by mpavlinov** [comment]
@rkaraivanov What's your progress on this?

**Comment by zdrawku** [comment]
ChangeDetectionStrategy should not be changed to OnPush, this introducec othre issues.

**Pull request closed without merging**
