### PR TITLE
unit test for multiple record changes

### PR DESCRIPTION
**Pull request by ighvarma**

### CODE REVIEW

**Comment by ighvarma** [comment]
@kdinev This request is the unit test.

**Comment by kdinev** [comment]
@ighvarma you could have included it to the other pull request :)

**Comment by kdinev** [comment]
@ighvarma I forgot to thank you for fixing this!

**Comment by kdinev** [comment]
@ighvarma I merged the fix with #64 but this test still fails. Can you check if the issue is with the test, or with the feature.

**Pull request closed without merging**
