### PR TITLE
Resize Observer Implementation for handling container/content size changes.

### LINKED ISSUE #4472: If a child grid is expanded and the display density changes, its horizontal scrollbar changes size when scrolled
## Description  
Changing the display density when a child grid has been expanded does not update its horizontal scrollbar until the user starts to scroll.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/display_density.html
2. Expand the first row - VINET
3. Change the density to Comfortable
4. Drag horizontally and observe the right end of the scrollbar

## Result  
The horizontal scrollbar shrinks when the scrolling starts

## Expected result  
The horizontal scrollbar should not be updated prior to scrolling

## Attachments  

ScrollbarShrink

### LINKED ISSUE #5305: Grid layout is broken when group by a some column and change density from comfortable to compact or cosy
## Description  

 * igniteui-angular version: 8.0.x; 8.1.x
 * browser: all

## Steps to reproduce  

1. Open grid group by dev sample
2. Press on the  button 'Toggle Density' 2 times until the grid's display density is set to 'comfortable'
3. Group by some column( "Company Name" for instance)
4. Press on the 'Toggle Density' button to change the grid density to 'compact'

## Result  
The grid layout is broken. There is big white space area.
image

## Expected result  
The grid should be sized correctly, no white spaces should be left.

### LINKED ISSUE #5340: When change column groupable to true the horizontal scroll dispersal
## Description  
When change column groupable to true the horizontal scroll dispersal 

 * igniteui-angular version: 8.0
 * browser: n/a

## Steps to reproduce  

1. Open the sample [link](https://stackblitz.com/edit/angular-wotpov-tqlxgd?file=src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html)
2. Click on button changeGroupable
3. Scroll vertocal

## Result  
As the groping is previewed the horizontal scroll is not longer visible

## Expected result  
The horizontal scroll should be visible

## Attachments  
image

### LINKED ISSUE #5529: igxGrid does not automatically respond to width and height adjustments that are not caused by a window resize
## Description  
Users are forced to call `reflow()` in scenarios where the grid has to respond to a transition, show/hide of a parent element, etc. This should be automatically handled by the grid with a resize observer.

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

TBA

## Result  

TBA

## Expected result  

TBA

*This is an overarching task that can be used to track progress. Issues that stem from the lack of this functionality will be linked below*
- #3639
- #4329
- #5508

Auto-size related issues:
- #4809
- #3950
- #3949
- #4758

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #5529  
Closes #5340
Closes #5305    
Closes #4472

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ChronosSF** [comment]
I'll be adding issues as I find them. Please, check those that are fixed.

**Comment by ChronosSF** [comment]
- [ ] Grid sample on Edge and FF - both width and height is slowly increased indefinately
- [ ] Resizing Sample - If you set width = null nothing gets rendered

**Comment by MayaKirova** [comment]
@ChronosSF please re-test.

**Comment by nrobakova** [comment]
I have found some issues in this PR:
- [ ] When columns has defined width and and maximum pinned area is extended in the toolbar is possibel to pin this columns. Steps to reproduce:
     1. Open dev sample gridSummary
     2. Check  showToolbar and columnPinning
     3. Pin first 4 columns
     4. Pin the 5th column.
It is checked but the column is not pinned, because the pinned area is extended
- [ ] When change column disablePinning the column is still previewed in the pinning toolbar. Steps to reproduce:
     1. Open dev sample gridSummary
     2. Check  showToolbar , columnPinning and disablePinning
     3. Open pinning toolbar
The column ReorderLevel is still previewed
- [ ] When search is applied and press tab on cell in edit mode the next cell is not in edit mode.  Steps to reproduce:
     1. Open dev sample gridSearch
     2. In the search type for example ana
     3. Double click on a cell in column CompanyName to open it in edit mode
     4. Press Tab key
Next cell is not in edit mode
- [ ] There is an empty space in the treeGrid when change displayDensity. Steps to reproduce:
     1. Open dev sample treeGridFlatData
     2. Click button rootAndChildLevels
     3. Scroll down that the row with id 15 be the first visible row
     4. Collapse row with ID 20
     5. Change displayDensity to compact
There is an empty space in the grid

**Comment by MayaKirova** [comment]
@nrobakova Previously logged issues can be re-tested for verification.

**Comment by nrobakova** [comment]
@MayaKirova all the logged issues are now resolved.

**Comment by ViktorSlavov** [comment]
@MayaKirova @ChronosSF 
The added package dependency does not seem to be present in the **library** `package.json`. When I tried to test the fix on an existing project (outside of the DevDemo one), I ran into a problem:
  1. in `igniteui-angular` root, run `npm i`, `npm run build:lib`
  2. `cd dist/igniteui-angular && npm pack`
  3. In another project (using our components), `npm i [location-to-tgz-file]`
  4. `npm run start` - fails with `could not find module 'resize-observer-polyfill'`

When testing the fix *inside* of the DevDemo project, the library package will find a definition of the `resize-observer-polyfill` on the repo's root level.
Should the `resize-observer-polyfill` be moved as a dependency in the **library** package.json or am I doing something wrong?

**Comment by MayaKirova** [comment]
@ViktorSlavov Resize observer should now be added to the main package json. Please re-test.

**Comment by ViktorSlavov** [comment]
@MayaKirova ,
Installing the package works fine now, thanks!
Everything else I tested with this branch also behaves as expected.

**Pull request merged**
