### PR TITLE
fix(themes): roundness and elevation scoping

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by SisIvanova — APPROVED** [review]

**Comment by hanastasov** [comment]
The fix is there in the latest stylesheet:
image

However, the highlighted part evaluates to 0px:
image

**Comment by hanastasov** [comment]
1) Go to the HR Portal App 
2) Inspect the first button under My Info view: Personal button
3) Change the border-radius to be
```scss
border-radius: clamp($min, calc(var(--igx-radius-factor) * var(--border-radius)), $max);
```
which is the value that comes with the current PR

Result: Border-radius is lost:
image

**Comment by pmoleri** [comment]
@hanastasov @simeonoff 
looks like `$min` and `$max` shouldn't be there at all, right?

**Comment by pmoleri** [comment]
All good, it turns out that the `$` issue was compiling with an outdated dart-sass version.
Updating from `1.35.2` to `1.49.1` fixed the issue. Probably due to changes around [`1.40.0`](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1401) and subsequent fixes that altered how expressions are used in `calc()`, `max()`, `min()`, `clamp()`.

**Pull request merged**
