### PR TITLE
Setting/hiding the label of a igx-datePicker

### PR DESCRIPTION
**Pull request by Hypenate**
[ZK Update] Issue #1519 will be closed after @Aleksandyr add 2 tests.  

Additional information related to this pull request:
Ability to set the label
Ablity to hide the label

### CODE REVIEW

**Comment by Hypenate** [comment]
Anyone willing the help me with the Travis CI build fail?
I don't know what's wrong.

**Comment by zdrawku** [comment]
"Type string trivially inferred from a string literal, remove type annotation" means that "public label: string = 'Date';" is redundant, you can ommit the "string" definition.

@Hypenate, keep in mind that we need to discuss this change first and then we can consider it as official (as I have explained in the associated issue).

**Comment by Hypenate** [comment]
@zdrawku Thank you to take the time for helping me out.
I read the conversation in #1519 but I wanted to 'understand' what was wrong with my build (I can't have my first-ever PR to fail 😄). It seems I read over the remark that you mentioned (oops).

Learned some new things today! Thank you (again).

**Comment by zdrawku** [comment]
3/3 nice, I am going to set "awaiting-test" label to this PR once we are ready with the decision whether to add these changes.

**Comment by zdrawku** [comment]
@Aleksandyr could you test these changes

**Comment by Aleksandyr** [comment]
@Hypenate Would you mind to write an unit test about your change which catch this exact scenario, because this is an important point of our process of adding a new feature? If you are not enough convenient with this I could get this initiative of adding this test.

**Comment by Hypenate** [comment]
@Aleksandyr I'm not sure how this works (and the date-picker.component.spec.ts file gives me a lot of errors). If there is a guide somewhere I would be happy to follow those steps.
But I gave it a shot and in the file mentioned I would add this (not sure if this is correct):

```
@Component({
    template: `
        <igx-datePicker [isLableVisible]="bool"></igx-datePicker>
    `
})
export class IgxDatePickerWithHiddenLabelComponent {
    public bool: boolean = false;
    @ViewChild(IgxDatePickerComponent) public datePicker: IgxDatePickerComponent;
}

@Component({
    template: `
        <igx-datePicker>{{label}}</igx-datePicker>
    `
})
export class IgxDatePickerWithSetLabelComponent {
    public label: string = "Subscriptiondate";
    @ViewChild(IgxDatePickerComponent) public datePicker: IgxDatePickerComponent;
}
```

**Comment by Aleksandyr** [comment]
@Hypenate I will take this part of the process and I will prepare these two test scenarios. Meanwhile you can go through [this](https://angular.io/guide/testing) guidance and take a brief understanding of how those spec.ts files should be configured.

**Pull request merged**
