### PR TITLE
Banner: Update the theme to reflect the latest designs in the UI kit

### PR DESCRIPTION
**Pull request by desig9stein**
Closes https://github.com/IgniteUI/igniteui-webcomponents/issues/1174

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by imincheva** [comment]
**Bootstrap**
- Same as in WebC the divider is adding up to the height of the Banner
- The default size should be medium _(ignore if irrelevant)_
- Banner-actions div should take the height from the nested buttons and shouldn't be fixed to 40px

**Comment by sbayreva** [comment]
**Fluent**
1. The height of the message container and the actions container here is 40px in all sizes. The size of theses containers should corresponds with the size of the used buttons ( small - 24px; medium -32px; large- 38px) as in Web Components.
2. The divider is adding up to the total height. It should be inside like it was implemented for the Web Components. Example from Angular:
Screenshot 2024-05-28 at 11 02 51

**Comment by AnjiManova** [comment]
**Material**

- same comments like Fluent and Bootstrap (divider + div height) + Irinka's comment about the default density

**Comment by sbayreva** [comment]
> **Fluent**
> 
> 1. The height of the message container and the actions container here is 40px in all sizes. The size of theses containers should corresponds with the size of the used buttons ( small - 24px; medium -32px; large- 38px) as in Web Components.
> 2. The divider is adding up to the total height. It should be inside like it was implemented for the Web Components. Example from Angular:
> 
> Screenshot 2024-05-28 at 11 02 51

Everything is applied!

**Comment by imincheva** [comment]
**All themes**
- Icon and Buttons should be medium by default

**Comment by desig9stein** [comment]
@kdinev This PR introduces visual-breaking changes to the banner component in all themes. Please verify that you are okay with these changes before we merge the PR:

The changes are:
-The default sizes of the action buttons and the icon have been adjusted.
-Padding values have been modified.
-Some colors have been updated.
-A border-bottom has been added to all themes except indigo.
- A min-width of 320px is added to the banner in all themes

Screenshot 2024-05-30 at 16 49 08

**Comment by kdinev** [comment]
@desig9stein Could you just tell me which is the old and which is the new one?

**Comment by desig9stein** [comment]
> @desig9stein Could you just tell me which is the old and which is the new one?

On the screenshot the new one has border-bottom

**Review by simeonoff — APPROVED** [review]

**Pull request merged**
