### PR TITLE
fix(pivot): Fix specifying filter in dimensions

### LINKED ISSUE #10742: [Pivot] Setting filtering expressions tree initially is not considered for the result
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by dkamburov**
Closes #10742 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
Initial filter expression is applied correctly but it does not get reflected in the excel style filter UI.
In the Pivot Grid sample, all fields except SellerName = Stanley are filtered out but in the UI they are all checked:

image

Only 'Stenley' should be checked.

**Comment by dkamburov** [comment]
Should be resolved now

**Comment by MayaKirova** [comment]
When initial filter is applied to column dimension the filtered out columns are still shown. For example when filtering out Countries, which is a column dimension in the pivot grid dev sample:

```
 this.filterExpTree.filteringOperands = [
            {
                condition: IgxStringFilteringOperand.instance().condition('equals'),
                fieldName: 'Country',
                searchVal: 'Bulgaria'
            }
        ];
```
All columns are still shown (even though values are not populated):

image

**Comment by dkamburov** [comment]
Just pushed a fix for this as well

**Comment by MayaKirova** [comment]
Regarding the last change:
```
const data = this.gridAPI.filterDataByExpressions(this.filteringExpressionsTree);
```

I think this should include only the filters currently  applied to the columns and not all filters. Because if a filter is applied in another dimension initially (for example SellerName in filters dimension) this will affect the generated columns (some will be filtered out), but consequent changes to the same filter will not trigger a re-initialization of the columns, hence the columns will remain filtered out even if that filter is changed or removed.

For example:
1)	Run the Pivot Grid sample, note that SellerName is filtered so only 1 column is displayed (Bulgaria).
2)	Open the SellerName filter and select all values.
Row data changes correctly but the columns remains just 1 ( the other columns don’t show even though now there is no filter).

**Comment by dkamburov** [comment]
Should be resolved

**Comment by dkamburov** [comment]
I've included all dimensions to be considered when updating the columns

**Pull request merged**
