### PR TITLE
fix(charts): wrong typography styles

### LINKED ISSUE #11707: Default Chart label styles are overriden by typography styles from library
Styles from typography break the chart label styles:

image

 * igniteui-angular version: 13.0.0
 *
1) Go to https://stackblitz.com/edit/angular-hqqn9j-dz4flv?file=src/styles.scss

See how label are bigger than expected and top edge of chart is cut off.

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #11707 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by simeonoff — APPROVED** [review]

**Review by simeonoff — DISMISSED** [review]

**Comment by hanastasov** [comment]
We also need same fix for text-style property for Pie chart

**Comment by SisIvanova** [comment]
> We also need same fix for text-style property for Pie chart

@sdimchevski Can you tell me what typography you use for the Pie chart in the  UI kits?

**Comment by hanastasov** [comment]
> > We also need same fix for text-style property for Pie chart
> 
> @sdimchevski Can you tell me what typography you use for the Pie chart in the UI kits?

I think it is the same as for the category chart titles/labels.

**Comment by sdimchevski** [comment]
@SisIvanova 

Titillium Web (Regular) 14px
Nunito Sans (Regular) 14px
Open Sans (Regular) 14px
Roboto (Regular) 14px

all are body 2, inactive

**Review by simeonoff — APPROVED** [review]

**Pull request merged**
