### PR TITLE
feat(pivot-grid): export to excel

### LINKED ISSUE #11742: [PivotGrid] Export to Excel
Similar to Data Grid, can the Pivot Grid have support for export to excel functionality?

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #11742   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
@onlyexeption, @igdmdimitrov 
When exporting the following configuration, I see no expander:
image
While there is one in some other configurations:
image

Also not sure, if that's an issue, but for the first one there is styling applied and for the other one there isn't.

**Comment by onlyexeption** [comment]
@dkamburov 

The styling is different because in the first example we have flat data that is exported in a table that styles are applied to. In the second example, we have multi column headers, so we don't export as table because Excel doesn't support it, hence the lack of styling, although I think we should style the multi column headers in the future.

**Comment by dkamburov** [comment]
@onlyexeption Okay, sounds like we can go with that note on the styling. What about the expand/collapse button in excel?

**Comment by onlyexeption** [comment]
@dkamburov when there's more than one filter field, the fields in the left (All product and City) look like vertical multi column headers. Currently, we don't have any logic that can export that type of structure. The current implementation exports those columns as regular ones instead of grouping them and this results in a file with flat data. I started working on supporting such kinds of structure.

**Review by ChronosSF — CHANGES_REQUESTED** [review]
Please, add a CHANGELOG entry for this.

**Comment by dkamburov** [comment]
@igdmdimitrov @onlyexeption there are build errors - looks like a circular ref.

**Comment by dkamburov** [comment]
@onlyexeption 
Exporting when there are no row dimensions, throws the following error:
image

**Comment by onlyexeption** [comment]
@dkamburov yes, currently the level property comes from the grid.filteredSortedData. That’s why it shows the level based on the last dimension. We can leave it this way or hardcode it to 0.

**Review by MayaKirova — DISMISSED** [review]

**Comment by ChronosSF** [comment]
@igdmdimitrov , @onlyexeption  , If the coverage falls I can merge it with it but we'll need to add automation to increase it in the very near future.

**Review by ChronosSF — APPROVED** [review]

**Pull request merged**
