### PR TITLE
Sorting styles improvemants

### LINKED ISSUE #3630: Sorting interaction improvements for active filter row
### Description  
When a grid has sorting and filtering enabled and the filtering is triggered to activate the filter row, we need to make it possible to sort the active column by clicking its header, or another one.
- [ ] Sort the current column while filter row is shown by clicking/tapping anywhere on the header
- [ ] Sort another column while filter row is shown by clicking/tapping only on the sort icon show on hover
- [ ] Show the filter row for another column by clicking/tapping on the header, area of sort icon shown on hover is excluded

Related to #2004.

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #3630 

 - [x] Styles
 - [x] Adding classes for sortable and filterable columns

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code

### CODE REVIEW

**Comment by kdinev** [comment]
@SAndreeva Who should verify this PR?

**Comment by kdinev** [comment]
@SAndreeva I know, I was asking whom to assign it to :)

**Comment by SAndreeva** [comment]
@sstoyanovIG  is the lucky one :)

**Comment by sstoyanovIG** [comment]
In Edge when a column or the sort indicator is clicked the header text blinks. Also after sort ascending, descending and then removing the sorting, the sort indicator disappears and the header text is no longer focused.

**Comment by desig9stein** [comment]
I think that the comment from @sstoyanovIG  is not related to the styling and should not stop this PR from being merged. However @sstoyanovIG you can create a bug related to Edge.

**Pull request merged**
