### PR TITLE
chore(grids): bump watermark version

### PR DESCRIPTION
**Pull request by damyanpetev**
(cherry picked from commit 38818ac3bfd128c526f4de962066c5ee6c9d7f87)

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

**Comment by kdinev** [comment]
@simeonoff The link icon is not visible at the moment:

image

**Review by kdinev — DISMISSED** [review]

**Comment by simeonoff** [comment]
> @simeonoff The link icon is not visible at the moment:
> 
> image

Interesting, I will take a look at what's going on.

**Comment by simeonoff** [comment]
> > @simeonoff The link icon is not visible at the moment:
> > image
> 
> Interesting, I will take a look at what's going on.

@kdinev I can't reproduce this. It works fine for me with version 3.0.1 in the context of the master branch.

image

**Comment by kdinev** [comment]
@simeonoff I'll try again and I'll let you know.

**Comment by simeonoff** [comment]
> @simeonoff I still get the same result. Could you try `rm -rf node_modules && nom install` and see if it's still fine on your end?

Did that and it's still visible for me in Chrome and Firefox. Fired up Safari and I encountered the problem - are you using Safari?

**Review by kdinev — DISMISSED** [review]

**Review by kdinev — APPROVED** [review]

**Review by kdinev — APPROVED** [review]

**Pull request merged**
