### PR TITLE
feat(pivot): Implement filters area dropdown

### LINKED ISSUE #10713: [Pivot] Implement filtering chips dropdown in PivotGrid UI
## Is your feature request related to a problem? Please describe.
Implement the filtering chips using the following design:
image

filtering dropdown when there are a lot of chips, that do not fit:
image

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #10713  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
@desig9stein When you have time can you please take a look and style the filtering dropdown according to the design from the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxPivotGrid-Specification)

**Comment by skrustev** [comment]
1. In the pivot sample an error is thrown `ERROR TypeError: Cannot read properties of null (reading 'style')` after dragging and dropping `AllSeller` chip from the filter area to the row dimensions area.

**Comment by dkamburov** [comment]
Please resolve conflicts

**Comment by dkamburov** [comment]
@desig9stein, @StefanIvanov We've investigated the failing tests in this PR, actually there are 5 failing tests into grid-filtering-ui.spec.ts. They seems to be introduced by the changed styles. It seems that they also apply for the filtering of other grids.
First ESF is the one with the new styles and the second one is with the old styles. The visual difference may be minor, but into the tests we can clearly see that the values container is smaller and the scrollbar size is different. In some cases the amount of the rendered values may differ.
image

Maybe some of the verifications are very strict, but still should we update the test expectations or consider this as a visual bug?

**Comment by desig9stein** [comment]
> @desig9stein, @StefanIvanov We've investigated the failing tests in this PR, actually there are 5 failing tests into grid-filtering-ui.spec.ts. They seems to be introduced by the changed styles. It seems that they also apply for the filtering of other grids. First ESF is the one with the new styles and the second one is with the old styles. The visual difference may be minor, but into the tests we can clearly see that the values container is smaller and the scrollbar size is different. In some cases the amount of the rendered values may differ. image
> 
> Maybe some of the verifications are very strict, but still should we update the test expectations or consider this as a visual bug?

I think that we should update the tests. I don't see any bug here.

**Pull request merged**
