### PR TITLE
fix(input-group): some japanese symbols don't fit the input box

### LINKED ISSUE #4752: igx-input: Top of Japanese characters get cut off in Density Compact mode
## Description  
When I type some Japanese characters in igx-input in Density Compact mode, top of characters get cut off as you can see the attached image.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open this sample: https://www.infragistics.com/products/ignite-ui-angular/angular/components/display_density.html
2. Select COMPACT mode
3. Copy "日日日" and paste it to First Name

## Result  
The top of the characters get cut off. This may be because Titilium isn't applied to Japanese characters, then the characters become bigger than expected character size.

## Expected result  
Japanese characters should be perfectly displayed as well.

## Attachments  
image

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #4752

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by jackofdiamond5** [comment]
@tkiryu I have tested the base functionality and it looks fine to me. Can you please check it out and tell us if you have any comments or if we should merge it right away.

**Comment by tkiryu** [comment]
@jackofdiamond5 , so sorry about that. I didn't noticed that this issue has been assigned to me. I'll check it out right away. I'll soon get back to you!

**Comment by tkiryu** [comment]
@jackofdiamond5 , I tested the fix to the all combinations of `igx-input-group` and displayDensities. the fix is OK for input text. But it is NOT OK for label text as placeholder.

Here is the results.
## Input text
### Compact: OK
image

### Cosy: OK
image

### Comfort: OK
image


## Label text as placeholder
### Compact: NG
image

### Cosy: NG
image

### Comfort: OK
image


Should I log as another issue about styling to label text?


## Attachements
[igx-input-group-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/3245515/igx-input-group-sample.zip)

**Comment by simeonoff** [comment]
> @jackofdiamond5 , I tested the fix to the all combinations of `igx-input-group` and displayDensities. the fix is OK for input text. But it is NOT OK for label text as placeholder.

@tkiryu hey, no need to log another issue. I will fix it in this PR. This will delay the PR by a bit, though.

**Comment by tkiryu** [comment]
@simeonoff , thanks! I'll test again after you fix it.

**Comment by simeonoff** [comment]
@jackofdiamond5 and @tkiryu I have pushed changes that should be able to fix the label. Can you confirm?

**Comment by tkiryu** [comment]
@simeonoff , label with input text has no margin to the top in the case of `compact` and `cosy`.

## Compact : NG
image

## Cosy : NG
image

##  Comfortable : OK
image

**Comment by tkiryu** [comment]
When I tried removing `marging-top` from `.igx-input-group__label` class, it looks better about `Box`, `Border` and `Search` types. On the other hand, it looks worse about `Line` type. Hmm, it's a bit difficult.
igx-input-group

By the way, I'm just wondering that there is a misalignment between `Line` type and the others. Is this expected behavior?
image

**Comment by simeonoff** [comment]
> By the way, I'm just wondering that there is a misalignment between `Line` type and the others. Is this expected behavior?

Nope, this is entirely by design. Just following the material design guidelines.

**Comment by tkiryu** [comment]
@simeonoff ,
>Nope, this is entirely by design. Just following the material design guidelines.
Thanks, I got it!

**Comment by kdinev** [comment]
@tkiryu Can you please take a look again with the latest changes?

**Comment by tkiryu** [comment]
@kdinev , OK! I'll test it again right now!

**Comment by tkiryu** [comment]
@kdinev , @simeonoff , my all tests has passed!

## Compact : OK
image

## Cosy : OK
image

## Comfortable : OK
image

**Pull request merged**
