### PR TITLE
fix(gird): actions order and border

### LINKED ISSUE #8570: Grid Pinning doesn't work with pinning config
## Description  
Columns don't get pinned where they are supposed when a pinning config is used

 * igniteui-angular version: 11
 * browser: n/a

## Steps to reproduce  

1. Open Grid Pinning Position demo - https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/grid/grid-sample-right-pinning

2. Pin several columns

## Result  
Columns don't get pinned where they are supposed to be and instead create empty space on the left.

## Expected result  
Should pin columns on the right

## Attachments  
Capture

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #8570 #8569

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ddincheva** [comment]
image
 Please notice that row drag and row expanders columns are switched!

**Comment by ChronosSF** [comment]
Nah @StefanIvanov already stated it was wrong in 10.2. The drag always comes first, then other stuff. I think expanders are actually last from the non-date cells. So RowSelectors should come between.

**Comment by ddincheva** [comment]
when the pinning configuration is set to end the pinned column is not visible. As described in #8570 
image

**Comment by desig9stein** [comment]
@ddincheva please test again with the latest change.

**Comment by ddincheva** [comment]
@desig9stein yes the problems are already fixed. Well Done!

**Review by simeonoff — APPROVED** [review]

**Review by ChronosSF — APPROVED** [review]

**Review by zdrawku — APPROVED** [review]

**Pull request merged**
