### PR TITLE
Add migrations for removed deprecated toolbar inputs in 13.0

### LINKED ISSUE #11593: No migration configs for removed IgxGrid members in 13.0.x
## Description  
The following inputs have been removed in `igniteui-angular v13.0.0` but there's no configs that mark the inputs to be removed by the migrations: `showToolbar`, `toolbarTitle`, `columnHiding`, `columnHidingTitle`, `hiddenColumnsText`,
        `columnPinning`, `columnPinningTitle`, `pinnedColumnsText`.

 * igniteui-angular version: `13.0.x`
 * browser:  n/a

## Expected result  
We should have configurations for all of the removed inputs.

## Attachments
PR where the inputs were removed - https://github.com/IgniteUI/igniteui-angular/pull/10297

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #11593   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by MayaKirova — DISMISSED** [review]

**Review by jackofdiamond5 — DISMISSED** [review]

**Comment by dkamburov** [comment]
@mddragnev The migration doesn't create `igx-grid-toolbar-exporter` component from `[exportExel]='true'`

**Comment by dkamburov** [comment]
I also noticed that the `igx-grid-toolbar-advanced-filtering` is not migrated from `[allowAdvancedFiltering]="true"`. But I guess we don't need migration for it as this property is not deprecated and removed.

@jackofdiamond5, @mddragnev Currently both ways to declare advanced filtering are supported:
- option `[allowAdvancedFiltering]="true"` in igx-grid
- inside toolbar actions as `igx-grid-toolbar-advanced-filtering`

Was it intended for the `@Input` `allowAdvancedFiltering` to be deprecated or removed as well or not?

**Comment by mddragnev** [comment]
@igdmdimitrov Could you please take a look at `allowAdnvacedFiltering` input and tell us if it is still there on purpose or just forgotten to be Deprecated?

**Comment by mddragnev** [comment]
Please keep in mind that https://github.com/IgniteUI/igniteui-angular/pull/11668 this should be merged before testing export migrations.

**Comment by igdmdimitrov** [comment]
> @igdmdimitrov Could you please take a look at `allowAdnvacedFiltering` input and tell us if it is still there on purpose or just forgotten to be Deprecated?

Not really sure. Maybe @rkaraivanov can shed some light on this as he was working on the toolbar refactoring.

**Comment by dkamburov** [comment]
@mddragnev Now that we have `14.0.x` we'll need the changes for that branch as well.

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
