### PR TITLE
Esf display density

### LINKED ISSUE #4833: Font-sizes in ESF do not match the font-size of the respective grid
## Description  
Font-sizes in ESF do not match the font-size of the respective grid.

This currently includes:
- **sort** and **move** headers (this should be considered for all display densities, currently the sort and move headers for '**comfortable**' and '**cosy**' are the same, while it is different for '**compact**')
- **clear filter** and **text filter** headers
- **text of the checkboxes** in the list items
- **dropdown items** from the cascade menu

We should also consider font-size changes for the custom filter dialog as well.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Run the 'Column moving' dev demo.
2. Switch to any display density.
3. Open the Excel Style Filtering component.
-> issue 1
3. Open the cascade menu for operators by clicking '**Text Filter**'.
-> issue 2
3. Open the Excel Style Custom Filtering dialog.
-> issue 3

## Result  

Issues 1,2,3: Font-size does **not** match the font-size of the respective grid.

## Expected result  

Issues 1,2,3: Font-size does match the font-size of the respective grid.

## Attachments  

esf

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #4833

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by tachojelev** [comment]
@simeonoff For **'compact'** density, the search component's scrollbar sinks down even when it has reached the bottom. If the list-item height in **'compact'** has changed with this PR, we should update the **itemSize** getter of the search-component.
list

**Comment by simeonoff** [comment]
> @simeonoff For **'compact'** density, the search component's scrollbar sinks down even when it has reached the bottom. If the list-item height in **'compact'** has changed with this PR, we should update the **itemSize** getter of the search-component.
> list

The only thing that's changed is the font size of the label in the checkbox. We've not touched the height of the item in compact mode.

**Comment by simeonoff** [comment]
@tachojelev Can you resolve the conflict? Also, what's holding this request from being pulled into master?

**Comment by StefanIvanov** [comment]
@tachojelev @gedinakova can you guys please resolve the conflict that @simeonoff asked for

**Comment by gedinakova** [comment]
@simeonoff @StefanIvanov Done.

**Comment by gedinakova** [comment]
What's holding this PR - no one has tested it.

**Comment by simeonoff** [comment]
> What's holding this PR - no one has tested it.

@gedinakova seems like tests are still failing.

**Pull request merged**
