### PR TITLE
feat(themes): add initial indigo theme

### LINKED ISSUE #7612: Create an indigo-inspired theme
Create a theme inspired by the indigo.design cloud experience and based on the UI Kits created specifically for the team working on that product.

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #7612 

### Covered Components, Directives, and Modules

- [x] **Action Srip** | [Handoff](https://xd.adobe.com/view/314e792d-e7b2-4498-b80f-4d65a0224545-641d/) | Asignee @desig9stein 
- [x] **Avatar** | [Handoff](https://xd.adobe.com/view/72dc6476-d32a-4be5-8ab1-caa6fc7ace0f-278f/) | Asignee @SisIvanova 
- [x] **Badge** | [Handoff](https://xd.adobe.com/view/57e28f94-a33f-458c-be48-b3923d08ef12-02b1/) | Asignee @didimmova 
- [x] **Banner** |  [Handoff](https://xd.adobe.com/view/2c7f5440-ec3e-42ca-a70d-cf8605ed7515-792c/) | Asignee @didimmova  
- [x] **Bottom Navigation** | [Handoff](https://xd.adobe.com/view/e1babf5f-0973-4e06-ac20-84f3512e88c2-b4e9/) | Asignee @SisIvanova 
- [x] **Button** | [Handoff](https://xd.adobe.com/view/7f7fc9aa-8ce4-4e07-a6d6-c8efe9ebce98-2a2c/) | Asignee @simeonoff 
- [x] **Button Group** | [Handoff](https://xd.adobe.com/view/7f7fc9aa-8ce4-4e07-a6d6-c8efe9ebce98-2a2c/) | Asignee @didimmova 
- [x] **Calendar** | [Handoff](https://xd.adobe.com/view/748c6101-31f1-459a-9645-73b08f678129-21df/) | Asignee  @simeonoff 
- [x] **Card** | [Handoff](https://xd.adobe.com/view/c9e77b9c-58c6-4d3d-802a-5513a563baca-9cb4/) | Asignee  @desig9stein 
- [x] **Carousel** | [Handoff](https://xd.adobe.com/view/af63754a-6581-4f9c-a787-f3e1096b6726-fa30/) | Asignee @SisIvanova 
- [x] **Checkbox** | [Handoff](https://xd.adobe.com/view/fec34e72-e6a3-4f18-b9e1-a62fc877da38-ab90/) | Asignee @didimmova 
- [x] **Chip** | [Handoff](https://xd.adobe.com/view/8937da5d-a70e-44c4-ab7d-4211c8334b34-dc64/) | Asignee @SisIvanova 
- [x] **Combo** | [Handoff](https://xd.adobe.com/view/3cd00916-1063-48a7-b2f2-de0282e2384e-6983/) | Asignee  @desig9stein 
- [x] **Date Picker** | [Handoff](https://xd.adobe.com/view/748c6101-31f1-459a-9645-73b08f678129-21df/) | Asignee @simeonoff 
- [x] **Date Range** | [Handoff](https://xd.adobe.com/view/748c6101-31f1-459a-9645-73b08f678129-21df/) | Asignee @simeonoff 
- [x] **Dialog** | [Handoff](https://xd.adobe.com/view/261ea49e-e12e-4749-973b-70d57b864bd5-734d/) | Asignee @desig9stein 
- [x] **Divider** | [Handoff](https://xd.adobe.com/view/314e792d-e7b2-4498-b80f-4d65a0224545-641d/) | Asignee @SisIvanova 
- [x] **Dock Manager** |  | Asignee @StefanIvanov  
- [x] **Drop-Down** | [Handoff](https://xd.adobe.com/view/6e936f87-44fe-4903-9f3e-c0ae21ab40b7-3bc0/) | Asignee @SisIvanova 
- [x] **Expansion Panel** | [Handoff](https://xd.adobe.com/view/2c7f5440-ec3e-42ca-a70d-cf8605ed7515-792c/) | Asignee  @didimmova 
- [x] **Grid** | [Handoff](https://xd.adobe.com/view/921576c5-81ea-481e-b985-6979691d32ab-c746/) | Asignee @simeonoff 
  - [x] Hierarchical Grid
  - [x] Tree Grid
  - [x] Toolbar
  - [x] Row Editing
  - [x] Footer w/ Summaries
  - [x] Pagination
  - [x] Advanced Filtering
  - [x] Excel Style Filtering
- [x] **Icon** | [Handoff](https://xd.adobe.com/view/833ac962-cfee-48f7-86ed-9c74fad8518b-d669/) | Asignee @SisIvanova 
- [x] **Input Group** | [Handoff](https://xd.adobe.com/view/8f98d0c2-2e51-4a7f-92bf-e41a8065b2e6-dacb/) | Asignee @desig9stein 
- [x] **List** | [Handoff](https://xd.adobe.com/view/fc5eb5a4-8a52-45b4-934e-75d8b4b8b29f-a90d/) | Asignee @didimmova 
- [x] **Navbar** | [Handoff](https://xd.adobe.com/view/e1babf5f-0973-4e06-ac20-84f3512e88c2-b4e9/) | Asignee @SisIvanova 
- [x] **Navdrawer** | [Handoff](https://xd.adobe.com/view/e1babf5f-0973-4e06-ac20-84f3512e88c2-b4e9/) | Asignee @desig9stein 
- [x] **Progress Indicators** | [Handoff](https://xd.adobe.com/view/e3654bb3-a6b3-487b-b9fd-d969cacb6139-b636/) | Asignee @simeonoff 
- [x] **Radio Buttons & Radio Group** | [Handoff](https://xd.adobe.com/view/8b231c4e-4935-4978-a486-7a1157bd2495-de70/) | Asignee @didimmova 
- [x] **Select** |  | Asignee @desig9stein 
- [x] **Slider** | [Handoff](https://xd.adobe.com/view/08062e74-3b3d-4154-9a1c-bc6df07ae0c1-5d55/) | Asignee @didimmova 
- [x] **Splitter** | [Handoff](https://xd.adobe.com/view/314e792d-e7b2-4498-b80f-4d65a0224545-641d/) | Asignee @SisIvanova 
- [x] **Snackbar** | [Handoff](https://xd.adobe.com/view/261ea49e-e12e-4749-973b-70d57b864bd5-734d/) | Asignee @didimmova 
- [x] **Switch** | [Handoff](https://xd.adobe.com/view/af9b2d3a-7028-447e-9984-adee0bddca05-fac8/) | Asignee @didimmova 
- [x] **Tabs** | [Handoff](https://xd.adobe.com/view/72770a07-d540-4df9-a03c-c1518d7fc573-2724/) | Asignee  @desig9stein 
- [x] **Time Picker** | [Handoff](https://xd.adobe.com/view/748c6101-31f1-459a-9645-73b08f678129-21df/) | Asignee @SisIvanova 
- [x] **Toast** | [Handoff](https://xd.adobe.com/view/261ea49e-e12e-4749-973b-70d57b864bd5-734d/) | Asignee  @didimmova 
- [x] **Tooltip** | [Handoff](https://xd.adobe.com/view/00ed2f75-9201-43e5-9b99-6fba56b92c19-55be/) | Asignee @didimmova 
- [x] **Mixins** | Adding theme mixins for indigo dark and light variant | Asignee @desig9stein 
- [x] **Watermark** | N/A | Asignee @simeonoff 
- [x] **Scrollbar** | [Handoff](https://teams.microsoft.com/l/file/45a6d989-42c0-492b-abd6-7a17422c68ed?tenantId=5467154b-1b75-4824-9369-916e4fb500db&fileType=docx&objectUrl=https%3A%2F%2Finfragisticsinc297-my.sharepoint.com%2Fpersonal%2Fsivanov_infragistics_com%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FScrollBar.docx&baseUrl=https%3A%2F%2Finfragisticsinc297-my.sharepoint.com%2Fpersonal%2Fsivanov_infragistics_com%2F&serviceName=p2p&threadId=19:meeting_ZDEwZjk0NjItMDM1YS00NzYzLWIzMDUtN2FjYjczMjNlMjg4@thread.v2) | Asignee @SisIvanova 
- [x] **Highlight** | [Handoff](https://teams.microsoft.com/l/file/99b60d7a-032e-4511-9346-54116c3b9d47?tenantId=5467154b-1b75-4824-9369-916e4fb500db&fileType=docx&objectUrl=https%3A%2F%2Finfragisticsinc297-my.sharepoint.com%2Fpersonal%2Fsivanov_infragistics_com%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FText%20Highlight.docx&baseUrl=https%3A%2F%2Finfragisticsinc297-my.sharepoint.com%2Fpersonal%2Fsivanov_infragistics_com%2F&serviceName=p2p&threadId=19:meeting_ZDEwZjk0NjItMDM1YS00NzYzLWIzMDUtN2FjYjczMjNlMjg4@thread.v2)| Asignee @didimmova   

#### Modules:
- [x] **Palettes** | [Handoff](https://xd.adobe.com/view/8e5a76b4-cc80-474c-bccf-784d18096777-db09/) | Asignee @simeonoff 
- [x] **Typography** | [Handoff](https://xd.adobe.com/view/937cc979-4d44-4220-b101-4dd4c3fb01d6-c62f/) | Asignee @simeonoff 
- [x] **Elevations** | [Handoff](https://example.com) | Asignee @simeonoff 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [x] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [x] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [x] This PR has a related DocFX Topic
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them
 
### Testing and Validation:
 - [x] Verify each schema(material, fluent, bootstrap) in both dark and light variants. Each theme should build, work, and look as it did prior to the introduction of the indigo theme.
 - [x] Test all themes in the Demo App, Samples App, and an app created with the CLI.
 - [x] Test the theme presets in a CLI app.
 - [x] Use both the `igx-theme` mixin and all theme wrapping mixins (ex. `igx-bootstrap-light-theme`) when validating the above scenarios.
 - [x] Verify the themes with `$legacy-support` turn both on and off.
 - [x] Build the Sassdoc documentation and verify we've not missed important theme properties.
 - [ ] Verify colors/contrast/typography using Chrome's Lighthouse accessibility tool.

### CODE REVIEW

**Comment by StefanIvanov** [comment]
Added Palettes and Typography @simeonoff

**Comment by StefanIvanov** [comment]
Added Avatar, Banner, Dialog, Snackbar, Toast @didimmova @SisIvanova @desig9stein

**Comment by StefanIvanov** [comment]
Added Navbar, Nav Drawer, Bottom Nav @desig9stein @SisIvanova

**Comment by simeonoff** [comment]
> Added Palettes and Typography @simeonoff

@StefanIvanov The palettes URL doesn't work for me.

**Comment by StefanIvanov** [comment]
Adding Button and Button Group @simeonoff @didimmova

**Comment by StefanIvanov** [comment]
Adding Combo, Drop-down, Calendar, Date Picker, Date Range Picker, Time Picker, Input Group
@desig9stein @SisIvanova @simeonoff

**Comment by StefanIvanov** [comment]
Adding List and Grid (here I expect that you will have questions because we never got to add all the grid features in the UI Kit but have quite a few that we can use as a starting point)
@didimmova @simeonoff

**Comment by StefanIvanov** [comment]
Adding Checkbox, Chips and Carousel
@didimmova @SisIvanova

**Comment by StefanIvanov** [comment]
Adding Icon and Hyperlink @SisIvanova

**Comment by StefanIvanov** [comment]
Adding Progress Indicators @simeonoff

**Comment by StefanIvanov** [comment]
Adding Radio, Switch and Tooltip @didimmova you are all set. Only the Expansion Panel is missing from your components but we will figure it out.

**Comment by StefanIvanov** [comment]
Adding Slider and Tabs @desig9stein

**Comment by StefanIvanov** [comment]
Adding Card @desig9stein

**Comment by StefanIvanov** [comment]
Adding Action Strip, Divider and Splitter @desig9stein @SisIvanova

**Comment by StefanIvanov** [comment]
Adding Banner and Expansion Panel @desig9stein @didimmova

**Comment by StefanIvanov** [comment]
Adding Scroll Bar and Highlight as textual files describing the properties @SisIvanova @didimmova

**Pull request merged**
