### PR TITLE
refactor(progress): update typography styles

### LINKED ISSUE #14350: Themes: Add typography for Linear and Circular progress

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #14350 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by SisIvanova** [comment]
@imincheva Please verify the typography styles for all themes for both linear and circular progress bars as well as the size/width/height of the components.

**Comment by imincheva** [comment]
### Linear Progress
**Bootstrap** 
- Track color in Dark Mode should be updated to grays.100 to match the rest of the themes and be consistent with the Circular Progress color
- Stripes color opacity should be updated to 20% in both Light and Dark Mode
- Stripes color in Dark Mode should be updated to grays.900 in Dark Mode
 
### Circular Progress ✅  
- There's a slight discrepancy, because the SVG size corresponds to the size of the component in the UI kits, but the circle elements inside are slightly smaller. IMO this is hardly noticeable, but I'm mentioning it, so we're on the same page.

_Please note that the color update suggestions shouldn't necessarily be implemented in this PR. I'm mentioning them here, because I'm verifying the component as a whole._

**Comment by imincheva** [comment]
In addition to my previous comment, after the latest updates in the UI kits, the following changes need to be applied here as well:

**Material**
- The size of the circular progress should be 32x32px and the typography should be:
image

**Fluent**
- The circular progress typography should be:
image

- Gap of 2px should be applied between the Linear Progress and its Value Label; The typography should be updated to Subtitle 2

**Comment by SisIvanova** [comment]
> ### Linear Progress
> **Bootstrap**
> 
> * Stripes color opacity should be updated to 20% in both Light and Dark Mode
> * Stripes color in Dark Mode should be updated to grays.900 in Dark Mode
> 
> ### Circular Progress
> * There's a slight discrepancy, because the SVG size corresponds to the size of the component in the UI kits, but the circle elements inside are slightly smaller. IMO this is hardly noticeable, but I'm mentioning it, so we're on the same page.
> 
> _Please note that the color update suggestions shouldn't necessarily be implemented in this PR. I'm mentioning them here, because I'm verifying the component as a whole._

The colors are fixed here https://github.com/IgniteUI/igniteui-theming/pull/296

**Pull request merged**
