### PR TITLE
fix(checkbox): tickmark not rendered correctly in indigo theme

### LINKED ISSUE #15021: Checkbox SVG icon displays incorrectly in applications with multiple themes
## Description  
The Checkbox SVG icon displays incorrectly in multi-theme applications when the wrapper’s default theme is set to indigo, causing the icon to render incorrectly for other themes within the wrapper component.
Related to - https://github.com/IgniteUI/igniteui-angular/pull/14520/files#diff-d8440ae54f8e381c947499499e892fd25029adfe3c7839f523ebb194a43a4090

 * igniteui-angular version: 18.2.x
 * browser: all

## Steps to reproduce  

1. Create an application using multiple themes.
2. Set 'Indigo' theme to the main component/wrapper.
3. Add a component utilizing different theme .e.g Material inside of the main wrapper.
4. Add checkbox component and observe the result

## Result  
What is the actual result after following the steps to reproduce?
Checkbox is loaded with the indigo svg path instead of the correct one.
image

## Expected result  
The correct icon to be displayed based on component theme.

## Attachments  
Theme used in main wrapper:
image
Thems used for the component: 
image

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #15021 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by simeonoff** [comment]
@desig9stein Please, also validate all themes look and work correctly, not just indigo.

**Comment by simeonoff** [comment]
@dobromirts Interesting, it works in the dev demos, perhaps something else is triggering change detection there. Will update it as you suggest and push soon.

**Comment by simeonoff** [comment]
@dobromirts Can you validate the implementation again?

**Comment by dobromirts** [comment]
> @dobromirts Can you validate the implementation again?

@simeonoff Thank you! Everything is working perfectly.

**Pull request merged**
