### PR TITLE
Typo in the documents

### LINKED ISSUE #1678: ng build ignuteui-angular -> Workspace cannot be found
### Description  
1. `npm install`
2. Then I went trough [Building the Library](https://github.com/Hypenate/igniteui-angular/blob/master/README.md#building-the-library)

But `ng build ignuteui-angular` does not exists...
Can you see the typo? 👻

### LINKED ISSUE #1680: igx-list Show load message
### Description  
Show a (custom) message that the data is being retrieved by setting a `isLoading` to `true` (and setting `loadingListMessage`).

### Result  
A message is shown when the data is being retrieved.
It would be nicer to show the igx-circular-bar that would keep on running but I was not able to make that.

### Note
Important to differentiate that it's not the list that is loading but the data is being retrieved by the back-end.

### PR DESCRIPTION
**Pull request by Hypenate**
Closes #1678 .  
Closes #1680 
Closes #1681 

Additional information related to this pull request:
gnuteui-angular to igniteui-angular

### CODE REVIEW

**Comment by kdinev** [comment]
@Hypenate This PR has all the changes in #1681, so I will leave this one open and close the other one.

**Comment by kdinev** [comment]
@Hypenate Could you also add the following to the `CHANGELOG.MD` under `6.1.0`:

 - List now exposes `emptyListMessage` and `loadingListMessage` inputs.

**Comment by kdinev** [comment]
@Hypenate We discussed this a little more and I've posted an update in the issue. We think there's an even better way to handle this scenario.

**Comment by Hypenate** [comment]
Sorry @kdinev, I f-up with the commits.
I have read the update, a loading indicator would be a nice way!

**Comment by kdinev** [comment]
@Hypenate Do you want to try implementing the adjustments @gedinakova suggested in the issue?

**Comment by Hypenate** [comment]
@kdinev I will give it a go when I have some spare time (maybe in the weekend).
Thanks @gedinakova  for the guide!

**Comment by Hypenate** [comment]
Hmm, I did an ng-serve before the push.. seems it added allot of extra things... 😭

**Comment by kdinev** [comment]
@Hypenate Seems like you force-pushed your version, overriding changes that have been applied in master since the last time you pulled. 

Do the following: 
1. Even your master with the upsteam master
2. Branch from the new master
3. Apply your changes to the branch you just created `git cherry-pick 9f017d2`
4. Do git pull upstream master before pulling
5. Execute npm run test:lib
6. Issue the pull request

**Comment by kdinev** [comment]
@Hypenate I cherry-picked your changes into a new branch. I will create a new pull request with them, closing the current PR and applying the changes.

**Comment by Hypenate** [comment]
@kdinev Thank you.
I tried, I had both the last version and my changes, but I was unable to push.
This can be closed?

**Pull request closed without merging**
