### PR TITLE
fix(igxGrid): Fixing ivy timing issue with change detection when rows…

### LINKED ISSUE #6244: When there is a grouped column search text is not highlighted
## Description  
When there is a grouped column search text is not highlighted 

 * igniteui-angular version: 9.0
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridSearch
2. Group by column 'CompanyName'
3. Collapse all
4. In the search type 'ana'

## Result  
Тhe search result in the second row is not highlighted 

## Expected result  
the search result should be highlighted 

## Attachments  
search

### PR DESCRIPTION
**Pull request by MayaKirova**
… are loaded from cache and active styles need to be re-applied.

Closes #6244   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by rkaraivanov** [comment]
I really dislike the piling of workarounds here.

**Comment by MayaKirova** [comment]
> I really dislike the piling of workarounds here.

Me too. The most obvious solution would be to trigger a full change detection when cached views are added so that everything is rendered before states are re-applied, however that has a negative impact on the performance. I'm open to suggestions if you have any.

**Comment by rkaraivanov** [comment]
> > I really dislike the piling of workarounds here.
> 
> Me too. The most obvious solution would be to trigger a full change detection when cached views are added so that everything is rendered before states are re-applied, however that has a negative impact on the performance. I'm open to suggestions if you have any.

Maybe something along those lines
https://github.com/IgniteUI/igniteui-angular/pull/6056/commits/4c3e95e2f74a6e7b7b546452f789e888b4a9b259

**Comment by MayaKirova** [comment]
@rkaraivanov Thanks for the idea. I've updated the PR based on your suggestion.

**Comment by rkaraivanov** [comment]
Alt Text

**Pull request merged**
