### PR TITLE
fix(igxGridFiltering): not possible to interact correctly with calendar

### LINKED ISSUE #1177: It is not possible to pick year and month through the year or month selector in filtering calendar.
### Description  
It is not possible to select different year and month through the year or month selector in filtering calendar.

### Steps to reproduce  
1. Open https://angular-c5hdty.stackblitz.io
2. Toggle filtering dropdown
3. Click on the input to open the calendar
4. Select another year or another month

### Result  
The calendar is not allowing you to select another value for year or month

### Expected result  
It should be possible to select different year and month.

### Attachments  
broken_calendar

### LINKED ISSUE #1183: Filtering calendar is not rendering after horizontally scrolling the igxGrid
### Description  
Filtering calendar is not rendering after horizontal scroll

### Steps to reproduce  

1. Open https://angular-c5hdty-wvun1s.stackblitz.io
2. Scroll to the end
3. Open filtering toggle
4. Click on the input or the calendar icon

### Result  
The filtering calendar not showing up

### Expected result  
The filtering calendar should be rendered

### Attachments  
calendar_not_available_after_scroll

### PR DESCRIPTION
**Pull request by Aleksandyr**
not possible to interact properly with calendar opend through datePicker
located into filteringUI dropdown

Closes #1177 
Closes #1183

### CODE REVIEW

**Comment by ddincheva** [comment]
despite the decrease coverage, there added two additional tests to check this fix.

**Comment by kdinev** [comment]
@Aleksandyr Is there a PR to `master`?

**Comment by Aleksandyr** [comment]
@kdinev There is no PR to `master` because there is some fixes about virtualization that are going to be pushed for 5.4.x v. So those fixes will fix the issue and these changes won't be necessary for `master`.

**Comment by Aleksandyr** [comment]
@kdinev I'm going to prepare the pull request for `master` and when the changes about virtualization came we are going to remove the code related to this fix.

**Pull request merged**
