### PR TITLE
fix(Grid): #3513 Fixed items' percentage width calculations.

### LINKED ISSUE #3513: Horizontal scrollbar is not shown when column's width is set to a percentage value.
### Description  
Describe the issue.

 * igniteui-angular version: 7.1.x, 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Start Dev Demos
2. Go to Grid Selection Demo
3. Set the first column width to 80%

### Result  
The last column gets partially out of view but the horizontal scrollbar is not shown.

### Expected result  
Horizontal scrollbar should be shown as the sum of columns' widths becomes greater than the grid's width.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
image

### PR DESCRIPTION
**Pull request by gedinakova**
Closes #3513   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
@gedinakova The igxFor does not handle width in % since if widths are in % the expected result would be for all columns to fit in the available space, hence there would be no virtualization (everything will be rendered as is).

In the following setup of the sample:
<igx-grid [width]="'800px'" …
        <igx-column [field]="'ProductID'" [editable]="true" [width]="'80%'"></igx-column>
        <igx-column [field]="'ProductName'" ></igx-column>
        <igx-column [field]="'UnitsInStock'"></igx-column>

I would expect the grid to resolve this to the following widths: 80%, 10%, 10% (which if set renders correctly).
Currently somewhere the grid calculations fail and it renders: 80%, 360px, 360x. The fix should probably be applied to the grid so that it resolves the % widths correctly.

**Comment by gedinakova** [comment]
@MayaKirova Thanks, I will review the calculations made by the grid. Please, note, though, that the calculated items' widths would still be wrong because with a value of '80%' the igxFor would get just the 80 and add it to the total width, which also seems wrong.

**Comment by MayaKirova** [comment]
@gedinakova @ChronosSF
I don’t think % is a valid value for it in the first place.
In general none of the igxFor inputs allow setting a value in %, all of the size related inputs expect number or px (igxForContainerSize, igxForItemSize), which is explicitly stated in their API.
Probably a better way to handle this would be for the grid to transform the value to px before passing it to the igxFor (like it does for the igxForContainerSize in case the grid width is set in %). In that case it may be possible to also support mixed widths correctly (some values in pixels, some in %).

As for what the expected result should be if someone sets % value in a stand-alone igxFor directive, I suppose either it should throw an error as it is invalid setting, or simply set its size to 0. Since none of the other size calculation expect or handle scenarios where % is used it doesn’t really make sense for the widths to be an exception and convert the value to pixels.

 Let me know what you think.

**Comment by gedinakova** [comment]
As discussed reassigning to @ChronosSF to review the grid's code as opposed to making such a change in IgxForOf.

**Pull request closed without merging**
