### PR TITLE
feat(slider): implement indigo slider changes

### PR DESCRIPTION
**Pull request by didimmova**
Related to [this issue](https://github.com/IgniteUI/igniteui-webcomponents/issues/1213)

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by sbayreva** [comment]
The space between the Tickmarks and the track should be 4px, now what I find is “bottom: 0.1875 rem” which in px is 3. I am not sure if it takes another 1px  from somewhere.
Screenshot 2024-05-30 at 10 15 38

**Comment by didimmova** [comment]
> The space between the Tickmarks and the track should be 4px, now what I find is “bottom: 0.1875 rem” which in px is 3. I am not sure if it takes another 1px from somewhere. Screenshot 2024-05-30 at 10 15 38
> 
> @andiesm813 , please check if there is anything else you want to add.

Because initially the bottom was 0 and the space was 7px, I moved it 3px to the top, so now it's 4px.

**Comment by sbayreva** [comment]
> > The space between the Tickmarks and the track should be 4px, now what I find is “bottom: 0.1875 rem” which in px is 3. I am not sure if it takes another 1px from somewhere. Screenshot 2024-05-30 at 10 15 38
> > @andiesm813 , please check if there is anything else you want to add.
> 
> Because initially the bottom was 0 and the space was 7px, I moved it 3px to the top, so now it's 4px.

Everything is verified by my side. Waiting for @andiesm813 approval.

**Review by SisIvanova — APPROVED** [review]

**Comment by andiesm813** [comment]
All good to me here as well! ✅✅✅

**Pull request merged**
