### PR TITLE
fix(Input): #3641 Remove the '' from input value setter.

### LINKED ISSUE #3641: Required date picker bound to displayData is shown invalid initially.
### Description  
Required date picker is shown with the invalid style applied even before being touched when the input is bound to displayData instead of value.

 * igniteui-angular version: 7.1.x, 7.2.x
 * browser: N/A

### Steps to reproduce  

1. Run https://stackblitz.com/edit/datepickerdemo-issue 
2. Note the two date pickers

### Result  
End date is shown invalid while Start date is not.

### Expected result  
End date should not be marked invalid.

### PR DESCRIPTION
**Pull request by gedinakova**
Closes #3641   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by SAndreeva** [comment]
Still marked as invalid on initial display, when using `ngModel` inside the template.

**Comment by gedinakova** [comment]
@SAndreeva This is how the standard input behaves as well so I suggest we leave this as is.

**Comment by kdinev** [comment]
@gedinakova Would this revert the behavior back to before #3624 was fixed?

**Comment by gedinakova** [comment]
@kdinev No, it would not. I tested all samples from the initial issue and there seems to be no problem there.

**Pull request merged**
