### PR TITLE
Add rowAdd and rowDelete events

### LINKED ISSUE #9993: Add `rowAdding` event to match editing event sequence for adding

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #9993 #9994 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — CHANGES_REQUESTED** [review]
Can we rename those to `rowAdding` and `rowDeleting` to avoid any ambiguity.

**Comment by mddragnev** [comment]
> ambiguity
@hanastasov 
I was following the row editing naming convention so they are consistent. Anyway, I will rename them

**Review by hanastasov — DISMISSED** [review]

**Comment by hanastasov** [comment]
Let;s keep the event `rowAdd`, `rowDelete` in order to comply with `rowEdit`

**Review by ChronosSF — APPROVED** [review]

**Review by ChronosSF — CHANGES_REQUESTED** [review]
Please, add a Changelog for these changes (for 12.2.0)

**Review by ChronosSF — APPROVED** [review]

**Pull request merged**
