### PR TITLE
Multi-row layout - Pinning feature integration

### PR DESCRIPTION
**Pull request by MayaKirova**
Note: This should be reviewed and merged after the main MRL feature is merged to master:
https://github.com/IgniteUI/igniteui-angular/pull/4486

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by PavlovVasil** [comment]
There are two issues I found while testing. Try this template for the grid-mrl.sample.html:
```
<section style="height: 600px" class="sample-content">
        <igx-grid 
        [rowSelectable]="false" 
        #grid
        [data]="data" 
        displayDensity="compact" 
        [width]="'1200px'" 
        [allowFiltering]="true" 
        [paging]='true'
        [filterMode]="'excelStyleFilter'">
            <igx-column-layout #block1>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="5" field="ContactName" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" field="ContactTitle" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="6" sortable="true" field="Country"[width]="'200px'"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block2>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" field="CompanyName"></igx-column>
                <igx-column [rowStart]="1" [colStart]="2" sortable="true" field="PostalCode"></igx-column>
                <igx-column [rowStart]="2" [colStart]="1" sortable="true" [colEnd]="3" field="Fax"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block3 [pinned]="true">
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="3" field="Phone"[width]="'200px'" ></igx-column>
                <igx-column [rowStart]="1" [colStart]="3" sortable="true" [colEnd]="5" field="City" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" [colEnd]="7" field="Address" [width]="'200px'"></igx-column>
            </igx-column-layout>
        </igx-grid>
    </section>
```
1. When a column group gets pinned, the 2px right border is not applied to the headers, but only to the records. This displaces the unpinned headers by 2 px to the left: 

Sketch


2. In MS IE 11, when using the same template, the headers get displaced and not rendered correctly. It is even more visible if ```#block2``` gets pinned as well: 

Sketch2

Sketch3

**Comment by dkamburov** [comment]
IE misalignments are not specific for the pinning only

**Comment by PavlovVasil** [comment]
The IE misalignments and 2px border have been fixed, but IE still does not render the headers correctly - if one group has two rows and the others do not, they are displayed as a single row with a blank row below it.
Using the same template from my previous reply: 
```<section style="height: 600px" class="sample-content">
        <igx-grid 
        [rowSelectable]="false" 
        #grid
        [data]="data" 
        displayDensity="compact" 
        [width]="'1200px'" 
        [allowFiltering]="true" 
        [paging]='true'
        [filterMode]="'excelStyleFilter'">
            <igx-column-layout #block1>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="5" field="ContactName" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" field="ContactTitle" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="6" sortable="true" field="Country"[width]="'200px'"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block2>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" field="CompanyName"></igx-column>
                <igx-column [rowStart]="1" [colStart]="2" sortable="true" field="PostalCode"></igx-column>
                <igx-column [rowStart]="2" [colStart]="1" sortable="true" [colEnd]="3" field="Fax"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block3 [pinned]="true">
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="3" field="Phone"[width]="'200px'" ></igx-column>
                <igx-column [rowStart]="1" [colStart]="3" sortable="true" [colEnd]="5" field="City" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" [colEnd]="7" field="Address" [width]="'200px'"></igx-column>
            </igx-column-layout>
        </igx-grid>
    </section>
```

IE renders the column headers like this: 

Sketch

**Comment by dkamburov** [comment]
This is not pinning specific, I logged a separate issue for it - https://github.com/IgniteUI/igniteui-angular/issues/4669

**Pull request merged**
