### PR TITLE
Column moving api master

### LINKED ISSUE #6334: Column Moving using API
## Ability to reorder columns using API
Current grid allow columns reordering via standard drag/drop mouse or touch gestures. It does not allow us to reorder based on saved preferences (somewhere.. say localstorage). 

Support must be added to set column position in a grid. 
1. `setColumnIndex(column: IgxColumnComponent, index: number)`: Set column position to index

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #6334 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [x] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [x] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by ddincheva — APPROVED** [review]

**Comment by hanastasov** [comment]
Open the Column Moving sample:

1) Select the ID column in the MCH grid
2) Try to move the ID column to index 2
Result: Column is not moved
Expected result: ID column should be moved between General Information and Address Information groups

1) Select the ID column in the MCH grid
2) Try to move the ID column to index 3
Result: ID column goes to last position, which is not index 3
Expected Result: ID column should not be moved, because position 3 is inside a group

**Comment by ddincheva** [comment]
There is still an issue: 
1. Move the ID column to 0 position
2. Try to move the ID column to index 3 // Result: Now the column is not moved
3. Try to move the column to index 9 // Result: the column is moved to position 2
Expected result: the column should be able to be moved to index 9 and became the last column in the grid

**Comment by ddincheva** [comment]
The problem described in the previous comment is fixed, but there are still issues like the following:
1. Click to column group "3"
2. Try to move the column to index 7

Result: the column is not moved
Also try to drag the column "3" to index 7 
Result: the grid layout is broken
columnMoving

1. Select the group column "Address information"
2. Try to move it to position 0

Result: the column is not moved

1. Select the group column "General information"
2. Try to move it to position 9

Result: the error is thrown on the console
columnMovingBug

**Comment by hanastasov** [comment]
> 
> 1. Click to column group "3"
> 2. Try to move the column to index 7
>
Not a bug. Should not be able to move, because it will receive index 6.

>
> 1. Select the group column "Address information"
> 2. Try to move it to position 0
> 
Choose selectedColumn.topLevelParent in the sample code, to work with the Address Information col.

> 
> 1. Select the group column "General information"
> 2. Try to move it to position 9
> 
> Result: the error is thrown on the console
> columnMovingBug
Resolved

**Comment by hanastasov** [comment]
Bugs:
Click to column group "3"
Try to move the column to index 6. Headers and cells are missalligned
https://github.com/IgniteUI/igniteui-angular/issues/8059

**Review by zdrawku — APPROVED** [review]
Except the issue #8059 with the misaligned headers, everything else looks perfect. Good work with the test coverage, Hristo!

**Pull request merged**
