### PR TITLE
Add templating option to the IgxPaginator Component

### LINKED ISSUE #9587: IgxPaginator Component should be templatable
## Describe the solution you'd like
I would like to be able to pass a custom-defined template to the paginator component.

### PR DESCRIPTION
**Pull request by ddincheva**
Closes #9587

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by rkaraivanov — DISMISSED** [review]

**Comment by rkaraivanov** [comment]
@ddincheva 
Can you resolve the conflicting files?

**Review by hanastasov — CHANGES_REQUESTED** [review]
As dicsussed with @ddincheva, let also fix the styles:

<igx-paginator>
    <igx-paginator-content>
        <igx-page-size-selector></igx-page-size-selector>
        <igx-pager></igx-pager>
    </igx-paginator-content>
</igx-paginator>

Should be enough for pager and select to be positioned as expected.

2. It makes more sense for `totalPages` to take precedence over `totalRecords`.

**Comment by ddincheva** [comment]
In this PR there are a few issues that should be addressed:

- [ ] The naming of the components and their selectors should be reviewed and possibly improved. Currently, they are introduced as IgxPageSizeSelectorComponent with a selector `igx-page-size-selector` and IgxPagerComponent - `igx-pager`;

- [ ] also maybe the wrapping div elements in these components are no longer necessary since the template is moved to a new wrapping component;

- [ ] currently as is pointed out in the previous comment the styling should be reviewed and changed in order to be easy to order all elements on the same row;

**Review by hanastasov — APPROVED** [review]

**Review by hanastasov — COMMENTED** [review]
To me, it seemed strange to have a `next` property in the `IPageCancellableEventArgs`:

image

When navigating to a previous page, `eventArgs` are:
{current: 1, next: 0, cancel: false}

What do you think about keeping it the same as `IPageEventArgs`

P.S. better to stay current/next for -ing event and current/previous for -ed event.

**Review by hanastasov — CHANGES_REQUESTED** [review]
Let's add documentation comment on the `IPageCancellableEventArgs` interface, so that doc page shows what each property stands for.

**Review by hanastasov — APPROVED** [review]

**Review by zdrawku — APPROVED** [review]

**Pull request merged**
