### PR TITLE
refactor: move DOCUMENT imports from platform-browser to common

### PR DESCRIPTION
**Pull request by badre429**
upgrade to angular 8 does not work because DOCUMENT does not imports from platform-browser any more
 
### Additional information (check all that apply):
 - [x] Bug fix

### CODE REVIEW

**Comment by kdinev** [comment]
@badre429 I'll retarget this PR to the `ng-8-update` branch.

**Comment by badre429** [comment]
this PR is not dedicated for angular 8 in this porject all instance of DOCUMENT are imported from @angular/common except for this file is importanted from @angular/platform-browser; 
then it still work with angular 7

**Comment by kdinev** [comment]
@badre429 In this case, I'll retarget to `7.3.x` as `master` is currently frozen. The change will make it into master with #4783

**Comment by kdinev** [comment]
@damyanpetev Can you verify that this file is even used anywhere because I have my doubts about that?

**Comment by damyanpetev** [comment]
@kdinev Yeah, it is in use (though long overdue for a refactor 😃)

**Pull request merged**
