### PR TITLE
fix(pivot): Do not clean state of data when using noop strategies

### LINKED ISSUE #10984: [Pivot] Having more child and sibling dimensions as row with noop strategies, the expanding does not work correctly
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot noop dev sample
2. set the data from the attached json
3. add this configuration
```
public pivotConfigHierarchy: IPivotConfiguration = {
        columnStrategy: NoopPivotDimensionsStrategy.instance(),
        rowStrategy: NoopPivotDimensionsStrategy.instance(),
        columns: [
            {
                memberName: 'Country',
                enabled: true
            },
        ]
        ,
        rows: [
            {
                memberFunction: () => 'All',
                memberName: 'AllProducts',
                enabled: true,
                width: '25%',
                childLevel: {
                    memberFunction: (data) => data.ProductCategory,
                    memberName: 'ProductCategory',
                    enabled: true
                }
            },
            {
                memberName: 'AllSeller',
                memberFunction: () => 'All Sellers',
                enabled: true,
                childLevel: {
                    enabled: true,
                    memberName: 'SellerName'
                }
            },
        ],
        values: [
            {
                member: 'UnitsSold',
                aggregate: {
                    aggregator: IgxPivotNumericAggregate.sum,
                    key: 'sum',
                    label: 'Sum'
                },
                enabled: true
            },
        ],
        filters: null
    };
```

Expand All products, Expand All Sellers, Expand Accessories All sellers

## Result  
The expansion is not correct

## Expected result  
The expansion should be correct

[data.txt](https://github.com/IgniteUI/igniteui-angular/files/8034077/data.txt)

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #10984 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
@mddragnev There is a failing test

**Review by dkamburov — DISMISSED** [review]

**Comment by 3phase** [comment]
@mddragnev,
If you sort a column, collapse the row dimensions and then attempt to expand them, the expansion indicator disappears and makes the dimension non openable.
Although the problem is also reproducible in master, I think it's related with the original issue you logged since it only happens when using a noop strategy. However, if you think it's not related, I can log it separately.

pivot-issue-5

**Comment by 3phase** [comment]
Besides that, a lag occurs when resetting a sort, as can be seen in the gif above.

**Comment by mddragnev** [comment]
> Besides that, a lag occurs when resetting a sort, as can be seen in the gif above.

@3phase I do not reproduce the lag, but will investigate the issue further

**Comment by 3phase** [comment]
@mddragnev 
The latter does not reproduce anymore.
However, if you try to move the column chip to the row dimensions. an error is thrown and nothing happens. This does not occur in master, so I believe it's something introduced here.

**Comment by mddragnev** [comment]
> @mddragnev The latter does not reproduce anymore. However, if you try to move a column chip to the row dimensions. an error is thrown and nothing happens. This does not occur in master, so I believe it's something introduced here.

With the current configuration it does reproduce in master too. If you reproduce it with this sample in master, you can log it separately because we do not need dimension moving in the sample in samples browser and I think it has nothing to do with the changes in this pr. I can take a look at it tomorrow.

**Comment by 3phase** [comment]
> > @mddragnev The latter does not reproduce anymore. However, if you try to move a column chip to the row dimensions. an error is thrown and nothing happens. This does not occur in master, so I believe it's something introduced here.
> 
> With the current configuration it does reproduce in master too. If you reproduce it with this sample in master, you can log it separately because we do not need dimension moving in the sample in samples browser and I think it has nothing to do with the changes in this pr. I can take a look at it tomorrow.

Ok, my mistake, I only tried by setting the column dimension as the one you gave in the description. It does reproduce in master when columnStrategy is set to `NoopPivotDimensionsStrategy`.

**Review by dkamburov — APPROVED** [review]

**Pull request merged**
