### PR TITLE
Fix cosy compact chip styling

### PR DESCRIPTION
**Pull request by desig9stein**
Related to #1846

### CODE REVIEW

**Comment by kdinev** [comment]
@desig9stein Is this still in development?

**Comment by desig9stein** [comment]
@kdinev  This fix is only for the styling part of the issue. There is other work that needs to be done in order #1846 to be closed.

**Comment by mpavlinov** [comment]
@desig9stein We cannot verify this PR without the other changes we need to do, that's why I put "in-development" status. We will add commits to this PR in order to close the #1846 .

**Comment by kdinev** [comment]
@desig9stein @MartinKamenov Can you guys move this to a branch in upstream, so you can both make the changes without switching remotes?

**Comment by mpavlinov** [comment]
@skrustev I guess this one is good for testing. Let me know if it's not.

**Pull request merged**
