### PR TITLE
fix(grid): headers should respond better to change in height

### LINKED ISSUE #4519: IgxGrid layout issue with global font settings
## Question  
I want to set font-size globally – e.g. 11px. Then the header layout of IgxGrid becomes broken. As you can see from the screenshot, the header cell height is not enough and there is a space underneath. How can I set font-size globally and use IgxGrid without issue?

image

You can see it on this sample.
https://stackblitz.com/edit/angular-timgrc?file=src/styles.scss

 * igniteui-angular version: 7.2.4
 * browser: n/a

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #4519

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by tkiryu** [comment]
@simeonoff , I tested the fix with the sample @ymita created. There was a misalignment among header titles.

test


`flex: 0 0 auto` should be applied to header title but it was overridden with `flex: 1 1 auto`. This is the reason of misalignment.

**Comment by tkiryu** [comment]
In order for `flex: 0 0 auto` to be applied to header title as expected, `%grid-thead-title` must be defined after `%grid-cell-header`;

In addition, I think `%grid-thead-item` should be inserted before the comment " We set those with position relative..." because this section has nothing to do with the comment.
```
    %grid-thead-item {
        display: flex;
        flex-flow: column nowrap;

        %grid-thead-group {
            flex: 1 1 auto;
        }

        %grid-cell-header {
            fle%grid-cell-headerx: 1 1 auto;
        }

        // %grid-thead-title must be after %grid-cell-header
        %grid-thead-title {
            flex: 0 0 auto;
        }
    }

    /* We set those with position relative
    so that the drop indicators be scoped
    to their respective group. The item
    being the topmost element, while the
    subgroup encapsulates children of each
    thead item and group.
    */
```

**Comment by tkiryu** [comment]
One more thing.  `height: auto` should be removed from `%grid-cell-header`.
https://github.com/IgniteUI/igniteui-angular/pull/5183/commits/402180f0f63cceca4130141e9d8c70f9981773f1#diff-3b297bce06352f50170a3270f84544b1R1168


`height: auto` affects not only `.igx-grid__th` but also `.igx-grid__thead-title`. Therefore, header title will get too low like this.

image

**Comment by tkiryu** [comment]
Two more things.

1. `%igx-grid__filtering-row` height should have the same as `%igx-grid__filtering-cell`. Otherwise, header text gets cut off when showing filtering row.

image

```
    %igx-grid__filtering-row {
        position: absolute;
        display: flex;
        width: 100%;
        // height: 50px;
        height: map-get($grid-header-height, 'comfortable');
        ...
```

**Comment by tkiryu** [comment]
Sorry about that. One last thing again.

I found that header text is a bit off to the top when dragging a header in this case(setting font-size globally – e.g. 11px. ). 

image

`align-self: flex-end` is applied to `%grid-cell-header-title`, which causes this. I think we can remove `align-self: flex-end` from `%grid-cell-header-title`.
```
    %grid-cell-header-title {
        ...
        // align-self: flex-end; 
        ...
    }
```

**Comment by rkaraivanov** [comment]
@tkiryu 
Can you re-test the misalignment issue with the latest changes in the branch?

**Comment by tkiryu** [comment]
@rkaraivanov , thank you. I tested. Your change is good for header auto sizing according to font size.

But it doesn't solve [the misalignment issue that I pointed out](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505709021).

[As I said avove](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505719575), code change to scss is needed.

**Comment by simeonoff** [comment]
> @rkaraivanov , thank you. I tested. Your change is good for header auto sizing according to font size.
> 
> But it doesn't solve [the misalignment issue that I pointed out](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505709021).
> 
> [As I said avove](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505719575), code change to scss is needed.

Thank you very much for your valuable input @tkiryu. I would be glad if you contributed your ideas directly to this PR. Contributions are not limited to the Sofia team only :)

**Comment by simeonoff** [comment]
> > @rkaraivanov , thank you. I tested. Your change is good for header auto sizing according to font size.
> > But it doesn't solve [the misalignment issue that I pointed out](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505709021).
> > [As I said avove](https://github.com/IgniteUI/igniteui-angular/pull/5183#issuecomment-505719575), code change to scss is needed.
> 
> Thank you very much for your valuable input @tkiryu. I would be glad if you contributed your ideas directly to this PR. Contributions are not limited to the Sofia team only :)

That being said, I will implement the suggested changes.

**Comment by tkiryu** [comment]
@simeonoff , 
>I would be glad if you contributed your ideas directly to this PR. Contributions are not limited to the Sofia team only :)

Will do from the next time 😄

**Comment by rkaraivanov** [comment]
@tkiryu
Can you recheck the sample with latest head of the branch?

**Comment by tkiryu** [comment]
@rkaraivanov , looks good 👍 Grid header is responsive to font size and has no misalignment.

Here is the results.

### Comfortable
image

### Cosy
image

### Compact
image

**Pull request merged**
