### PR TITLE
Indigo: Add Updates for Navdrawer, Navbar, and Switch

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #  

- [x] Bottom Navigation
- [x] Navbar
- [x] Navigation Drawer
- [x] Switch

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by andiesm813** [comment]
**NAVIGATION**
Hey guys! i made 2 last minute updates to 2 components here:

1. Changed the color of the header in the nav drawer dark mode.
2. Added a missing top stroke in the bottom navigation (something i realized while working on Tabs).

image

**Comment by imincheva** [comment]
**Bottom Navigation**
- Elevation should be 0 in both light and dark mode.
- There shouldn't be opacity on the disabled items. The colors also need to be updated: grays.900 20% opacity in light mode and white 20% in dark mode.
- In dark mode the color of the selected icon should be primary.200
- The stroke Andie mentioned is still missing. It should be 1px solid grays.300 in light mode and 1px solid grays.100 in dark mode

**Comment by AnjiManova** [comment]
**Navigation Drawer**

Dark Theme:
- Header color should be white 60% not grays.700
image image

**Comment by desig9stein** [comment]
@sbayreva 

> ### Navbar
> 1. The font style should be Heading 5

it is h5
Screenshot 2024-04-23 at 12 16 18


> 2. The sample with the **action icons**:
> * The action icons should be 16px which is medium size icon in Indigo theme. Each of these medium icons should be  within a 28px container. The space between the action icons should be 8px.

they are 28px with 8px gap 
Screenshot 2024-04-23 at 12 02 22
Screenshot 2024-04-23 at 12 02 40


> 3. The sample with the **icon buttons**:
> * The icon buttons should be in medium size (28px) and the space between each button should be 8px.

they are 28px with 8px gap 
Screenshot 2024-04-23 at 12 03 24
Screenshot 2024-04-23 at 12 03 45


> 4. The the navigation icons should be 16px which is medium size icon in Indigo theme and should be  within a 28px container.

it is 28px and the SVG is 16px
Screenshot 2024-04-23 at 12 14 17


> 5. Elevation 4 should be added to the whole component.

I changed it to 4, but in the UI kit, it looks like there is no elevation, that's why I don't even bother to look if there is an elevation in the first place.
Screenshot 2024-04-23 at 12 21 15

**Comment by desig9stein** [comment]
@imincheva 
> * In dark mode the color of the selected icon should be primary.200

In the UI kit, the icon is 300 and the text is 200

**Comment by imincheva** [comment]
> @imincheva
> 
> > * In dark mode the color of the selected icon should be primary.200
> 
> In the UI kit, the icon is 300 and the text is 200

In the base component they're both 200. However, I see that in the main bottom navigation component the colors aren't updated, which is probably a Figma glitch, but we'll investigate the issue.
image
image

**Comment by didimmova** [comment]
> **Navigation Drawer**
> 
> Dark Theme:
> 
> * Header color should be white 60% not grays.700
>   image image

should be fixed now the theming version is updated

**Comment by imincheva** [comment]
**Switch**
All looks good.

**Comment by sbayreva** [comment]
> @sbayreva pull latest changes and test again

Everything looks good with the Navbar! @andiesm813  please, confirm if everything is all right with the Navbar.

**Comment by andiesm813** [comment]
**NAVIGATION DRAWER**

The only thing i see pending to fix is the size of the "Overline" text style.
I found an ERROR (caused by me!) in the indigo ui kit figma file. There is a difference between the actual style and what's written here. The style is the correct and what's written it's not.

The correct style for Overline is:

- Font size: 11px
- Line height: 15px
- Font weight: bold (that is currently correctly implemented).

image

**Comment by andiesm813** [comment]
**NAVIGATION BAR**

1. Sample with icon buttons: The icon buttons should be medium size (they still look small size).
2. Sample with icons: those icons look huge compared to the design. So does the left action icon (menu icon or back arrow)

image

The icons should look identical to the size of the icons when used as "icon button":

image

3. There should be NO elevation. This is a mistake in the Figma file. I honestly did NOT realize there was an elevation applied to the navbar, since i truly cannot see it on the design surface (i do see in the property panel, that it's applied, but i didnt realize it till now). I'm sorry you guys implemented that. I will update the figma design.

image

**Comment by andiesm813** [comment]
**BOTTOM NAVIGATION**

All looks good to me.  ✅

**Comment by andiesm813** [comment]
**SWITCH**

1. There should be no resting, hover or disabled elevation / shadows applied. I dont know if they are really showing (dont see them), but maybe they should be set to elevation-0 if they need to remain in the css. 

image

2. The text looks vertically misaligned with the switch.... You can see the difference compared with the material theme.... i dont understand why this happens... maybe optical illusion?

image

3. Dark theme: 
The --track-on-hover-color should be primary-400. I know it's incorrect in the figma, but it's something i should have updated. I was waiting to update the Figma (per Irina's request). But it's something i will update soon. If you can fix it now it's ok. If not, i'll make a request afterwards.

**Comment by SisIvanova** [comment]
> **NAVIGATION DRAWER**
> 
> The only thing i see pending to fix is the size of the "Overline" text style. I found an ERROR (caused by me!) in the indigo ui kit figma file. There is a difference between the actual style and what's written here. The style is the correct and what's written it's not.
> 
> The correct style for Overline is:
> 
> * Font size: 11px
> * Line height: 15px
> * Font weight: bold (that is currently correctly implemented).
> 
> image

This problem is fixed here: https://github.com/IgniteUI/igniteui-theming/pull/255

**Comment by SisIvanova** [comment]
> **SWITCH**
> 
> 1. There should be no resting, hover or disabled elevation / shadows applied. I dont know if they are really showing (dont see them), but maybe they should be set to elevation-0 if they need to remain in the css.
> 
> image
> 
> 2. The text looks vertically misaligned with the switch.... You can see the difference compared with the material theme.... i dont understand why this happens... maybe optical illusion?
> 
> image
> 
> 3. Dark theme:
>    The --track-on-hover-color should be primary-400. I know it's incorrect in the figma, but it's something i should have updated. I was waiting to update the Figma (per Irina's request). But it's something i will update soon. If you can fix it now it's ok. If not, i'll make a request afterwards.

1. The elevations you are referring to are used only in the material theme. If you check the `.igx-switch__composite-thumb` element you will see `box-shadow: none`. 
Screenshot 2024-05-07 at 1 43 40 PM

3. This may be related to your resolution or the way you scale the screen. Both the thumb and the text are aligned horizontally using "align-items: center". 
Screenshot 2024-05-07 at 1 41 39 PM
Screenshot 2024-05-07 at 1 42 06 PM

Screenshot 2024-05-07 at 1 27 13 PM

4. The color is updated here: https://github.com/IgniteUI/igniteui-theming/pull/248/commits/8f45da4c12c304634245f1c0c479174e4e306340 but the change will be visible in this PR after a new version of the theming package is released.

**Comment by andiesm813** [comment]
**SWITCH & NAV DRAWER**
They both look good to me!  ✅✅

**Comment by andiesm813** [comment]
> **NAVIGATION BAR**
> 
> 1. Sample with icon buttons: The icon buttons should be medium size (they still look small size).
> 2. Sample with icons: those icons look huge compared to the design. So does the left action icon (menu icon or back arrow)
> 
> image
> 
> The icons should look identical to the size of the icons when used as "icon button":
> 
> image
> 
> 3. There should be NO elevation. This is a mistake in the Figma file. I honestly did NOT realize there was an elevation applied to the navbar, since i truly cannot see it on the design surface (i do see in the property panel, that it's applied, but i didnt realize it till now). I'm sorry you guys implemented that. I will update the figma design.
> 
> image
> 
> @sbayreva I saw what you meant about the navbar in light mode and the buttons. There's nothing i can do about it. If users can set the navbar to dark theme, while keeping the rest of the app light theme, that would be ideal. It's something we do a lot in apps in AB (mix light & dark themes, and lots of real life apps are designed like that).

**NAV BAR**
The only thing i see pending to fix is the elevation applied to the navbar, which i explained was an issue in the Figma, i hadnt noticed it had elevation. It's not supposed to have elevation.  My mistake on Figma, which i fixed alreay ;)

**Comment by SisIvanova** [comment]
> **NAV BAR** The only thing i see pending to fix is the elevation applied to the navbar, which i explained was an issue in the Figma, i hadnt noticed it had elevation. It's not supposed to have elevation. My mistake on Figma, which i fixed alreay ;)

@andiesm813 I believe the navbar has no elevation. The `box-shadow` property value is set to `var(--shadow)` and the shadow refers to elevation level 0. 

Screenshot 2024-05-09 at 12 03 50 AM

**Comment by andiesm813** [comment]
> > **NAV BAR** The only thing i see pending to fix is the elevation applied to the navbar, which i explained was an issue in the Figma, i hadnt noticed it had elevation. It's not supposed to have elevation. My mistake on Figma, which i fixed alreay ;)
> 
> @andiesm813 I believe the navbar has no elevation. The `box-shadow` property value is set to `var(--shadow)` and the shadow refers to elevation level 0.
> 
> Screenshot 2024-05-09 at 12 03 50 AM

Great!! i trust the code then! (in the sample i was running i still see it, but if the code is fine, i'll consider it fixed). Thanks!!!
Navbar ✅!

**Review by didimmova — APPROVED** [review]

**Review by didimmova — APPROVED** [review]

**Review by didimmova — APPROVED** [review]

**Pull request merged**
