### PR TITLE
Fix display density and horizontal button centering for the toolbar

### LINKED ISSUE #5002: [igx-grid] Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.
## Description  
Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

 * igniteui-angular version: 7.3.3
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-button-height-issue-in-toolbar

## Result  
Toolbar height for displayDensity = 'compact' is the same as the one for displayDensity = 'cosy'.

### Compact : NG
image

### Cosy : OK
image

### Comforable : OK
image

## Expected result  
Toolbar height for displayDensity = 'compact' should be smaller than the one for displayDensity = 'cosy'.

## Attachments  
None.

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #5002 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by tkiryu** [comment]
I tested. You can check these out.

- Comfortable: https://igx-grid-comfortable.netlify.com/
- Cosy: https://igx-grid-cosy.netlify.com/
- Compact: https://igx-grid-compact.netlify.com/

I'm feeling that
1. Toolbars are a bit too higher than the previous ones, especially `comfortable` one.
2. Toolbar title should align with row selector's checkbox. 

About 1, according to [material design data table spec](https://material.io/design/components/data-tables.html#specs) , header height is 64px. So I think toolbar height should be up to 64px as well.

About 2, I think left/right paddings of toolbars should  have the same padding of checkbox.
  - Comfortable: 24px
  - Cosy: 16px
  - Compact: 12px

@StefanIvanov, @DaniMarinov, @desig9stein , do you have any thoughts on these?

**Comment by DaniMarinov** [comment]
@tkiryu Thank you for your feedback. As to:
_1. Toolbars are a bit too higher than the previous ones, especially comfortable one._ - The reason I designed them was because of the Search Input that has height in Comfortable of 50px. Now, I updated it and explained in the spec that I recommend if users want to have Input in the toolbar, they can use Input in Cosy (check samples in the spec) or they can take it out from the grid as it is shown here 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search.html
Since, the toolbar has to have fixed height, I designed it with height in Comfortable of 58px which works well both with Cosy Input and Comfortable Buttons. IMO even 64px is quite a lot for Comfortable height.

_2. Toolbar title should align with row selector's checkbox._ - Totally agree with you, so I've updated it.

https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Toolbar-Specification

**Comment by tkiryu** [comment]
@DaniMarinov , thanks! I'v checked the [latest doc](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Toolbar-Specification#user-interface) and it looks much better than before. Thank you so much!

**Comment by desig9stein** [comment]
@StefanIvanov can you review the change that @DaniMarinov did before I start implementing it.

**Comment by StefanIvanov** [comment]
@desig9stein I have discussed with @DaniMarinov the spec updates as he was taking all the considerations in account and now that he has put them nicely into the spec I am confident that you can start the implementation

**Comment by desig9stein** [comment]
@tkiryu I've made the changes, you can test now.

**Comment by tkiryu** [comment]
@desig9stein , I tested. `Cosy` and 'Compact' toolbars were OK! But `Comfortable` toolbar didn't have correct padding. You need to change the following line as well.

https://github.com/IgniteUI/igniteui-angular/pull/5052/commits/7c870fbe4ca6e4ac85616c3e195b1530653bdfa8#diff-29d1f3a0aed126a575b4a56f0071f181R165

```
// Now
        padding: map-get($grid-toolbar-padding, 'cosy');

// After
        padding: map-get($grid-toolbar-padding, 'comfortable');
```

**Comment by desig9stein** [comment]
@tkiryu you can test again.

**Comment by tkiryu** [comment]
@desig9stein , congrats:smile: My test finally has passed!

**Comment by desig9stein** [comment]
@tkiryu @StefanIvanov @DaniMarinov Can some of you change the label from awaiting test to verified so that the PR can be merged.

**Pull request merged**
