### PR TITLE
Update grid-resources.ts

### PR DESCRIPTION
**Pull request by mrApptastic**
"Gitter" means "fence" in Danish:
https://ordnet.dk/ddo/ordbog?query=gitter (In Danish - sorry)
Hence, "Tabel" (Table) is a better translation. Perhaps even simply "No data" -> "Ingen data" would be better.

Closes #  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by kdinev** [comment]
@randriova Maybe this should just be changed to "No data" -> "Ingen data" as @mrApptastic suggests?

**Comment by randriova** [comment]
> @randriova Maybe this should just be changed to "No data" -> "Ingen data" as @mrApptastic suggests?

Sounds good to me. Once this change is merged we can apply it for the rest of the versions.

**Comment by kdinev** [comment]
@randriova Do you think the change should be applied only to Danish, or to all languages?

**Comment by randriova** [comment]
@kdinev Good point. I guess that if we choose to just switch 'Gitter' to 'Tabel', only Danish would be affected, but if we re-write the entire sting as 'No Data', we might have to change it for the rest of the languages for consistency. It won't be a problem for Localization in any of the cases.

**Comment by kdinev** [comment]
@randriova OK, for the sake of not creating a large change, let's just merge the current change. I'll go ahead and approve it. We will propagate it to `12.1.x`.

@mrApptastic Could you please branch off of `12.1.x` and cherry-pick your changes and then create one more PR against `12.1.x`?

**Review by kdinev — APPROVED** [review]

**Pull request merged**
