### PR TITLE
[groupby] page both group rows and records - master

### LINKED ISSUE #5089: Show all grid rows on grouping if paging is enabled
## Is your feature request related to a problem? Please describe.
If a grid has both paging and grouping, groups are not shown if they only exist on other pages than the current page.

image

## Describe the solution you'd like
While grouping is on, it would be nice to have the option to ignore paging, in order to make sure that all group headers are shown.

## Describe alternatives you've considered
I tried a solution where I simply increase the "perPage" from let say 100 to 1000 (max rows returned from the API) property in the onGroupingDone event. This works fine when applying grouping, but when the grouping is removed, it will render all 1000 rows (since the event is onGroupingDONE). Would it be possible to expose a onGroupingStarting event or similar? The old igniteui grid did have a lot more events in this regard, iirc? Note that we can't use virtualization for this grid, as we want to avoid double scrollbars on the page.

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #5089

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [x] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by VMihalkov** [comment]
I found 1 issue. Here are steps to reproduce:

1. Set paging to true in the "Grid GroupBy" dev sample
2. Set Items per page to 10
3. Filter by country
4. Go to the last page (should be 4)
5. Click the button to collapse all the groups
6. You remain on page 4 of 2 total pages

**Comment by ChronosSF** [comment]
> Issue 1:
> 
> 1. Set paging to true in the "Grid GroupBy" dev sample
> 2. Set Items per page to 10
> 3. Group by Country
> 4. Go to the last page (should be 4)
> 5. Click the button to collapse all the groups
> 
> Result: You remain on page 4 of 2 total pages
> 
> Issue 2:
> 
> 1. Set paging to true in the "Grid Column Groups" dev sample and set displayDensity to "cosy"
> 2. Set Items per page to 5
> 3. Group by ContactTitle
> 4. Click the CollapseAll button to collapse all the groups
> 5. Expand "Marketing Manager" group
> 6. Go to the next page
> 7. Return to the first page
> 
> Result: "Marketing Manager" group header is missing
> GroupHeaderMissing

Addressed in latest commit.

**Comment by VMihalkov** [comment]
Found new issue: When 2 or more columns are grouped and all the groups are collapsed, the total number of pages is incorrect. Steps to reproduce:

1. Set paging to true in the "Grid GroupBy" dev sample
2. Set Items per page to 10
3. Group by Country
4. Click the button to collapse all the groups
5. Group by City
Result: The total number of pages changes to 4, but the actual pages are 2

**Comment by ChronosSF** [comment]
@VMihalkov , @mpavlinov - all current issues are solved in latest commit

**Pull request merged**
