### PR TITLE
fix(pivotGrid): Preserve row dimension sizes in percents when resizing a column.

### LINKED ISSUE #10875: [igxPivot] Row dimension width in percentage get transformed into pixels in users configuration
## Description  
Currently when the width is set to percentage, it gets transformed to pixels in the pivot configuration. We should maintain the user configuration if it is in percentages

Related to #10717

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the pivot grid sample
2. Set row dimension width to percentage
3. Resize that row dimension

## Result  
The width in the pivot configuration is changed to pixels

## Expected result  
It should remain in percentage

### PR DESCRIPTION
**Pull request by skrustev**
Closes #10875

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by MayaKirova — APPROVED** [review]

**Review by mddragnev — APPROVED** [review]

**Comment by 3phase** [comment]
@skrustev, although the functionality works well, the builds are failing for some reason. Fyi, I updated a leftover in `pivot-row-dimension-content.component.html`. Could this be the reason?

**Review by MayaKirova — DISMISSED** [review]

**Review by mddragnev — APPROVED** [review]

**Comment by dkamburov** [comment]
@skrustev Please resolve conflicts

**Comment by dkamburov** [comment]
@skrustev please resolve conflicts

**Review by MayaKirova — APPROVED** [review]

**Review by mddragnev — DISMISSED** [review]

**Comment by dkamburov** [comment]
@skrustev there is a build error

**Review by mddragnev — APPROVED** [review]

**Pull request merged**
