### PR TITLE
fix(IgxGrid): Add checks in case cell is no longer in view.

### LINKED ISSUE #14116: Grids: Cell node might be undefined after scroll - error in crud service updateCell
## Description  
In the `IgxGrid` editing a cell, then scrolling while the cell is in edit mode and then clicking somewhere throws an error.
I believe this behavior is related to the fix of [this issue](https://github.com/IgniteUI/igniteui-angular/pull/14026), as the error is thrown from the introduced lines.

 * igniteui-angular version: 17.1.x
 * browser: any

## Steps to reproduce  

1. Open this sample or any other having an `IgxGrid`/`IgxTreeGrid`,.. with editable cells and enough records to scroll.
2. Edit a cell.
3. Without exiting edit mode scroll down.
4. Click on any cell.

## Result  
At this point the edited cell changes have to be committed, however, an error is thrown.
```
polyfills.js:11947 Uncaught TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at IgxGridCRUDService.updateCell (vendor.js:131558:104)
    at IgxGridCellComponent._updateCRUDStatus (vendor.js:186695:46)
    at IgxGridCellComponent.activate (vendor.js:186596:27)
    at IgxGridCellComponent.pointerdown (vendor.js:186386:12)
```

## Expected result  
No error.

## Attachments  
issue-repro

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #14116   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by mddragnev — APPROVED** [review]

**Comment by mddragnev** [comment]
@MayaKirova I think we also need a PR for 16.1.x

**Comment by MayaKirova** [comment]
@mddragnev I think 16.1.x already has all the commits: https://github.com/IgniteUI/igniteui-angular/pull/14220/commits

**Comment by mddragnev** [comment]
> @mddragnev I think 16.1.x already has all the commits: https://github.com/IgniteUI/igniteui-angular/pull/14220/commits

Isnt this a different issue and PR?

**Comment by MayaKirova** [comment]
> > @mddragnev I think 16.1.x already has all the commits: https://github.com/IgniteUI/igniteui-angular/pull/14220/commits
> 
> Isnt this a different issue and PR?

Yes. My bad.

**Pull request merged**
